### ISSUE TITLE
Need to add an export to csv button to data table

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#101]
## Request - We had a hackday and our idea won - it was adding a export to csv button to the data table. So my manager said it would be better if we just added the export button to the data table itself in carbon and try get that into source

@SimonFinney told me to raise this for further discussion.

### Details

- **Application / team -** 
- **Work item -** []()
- **Needed by -** 

### Proposal

![]()
Like below - added in an export icon

![image](https://user-images.githubusercontent.com/55839633/65688773-905e6400-e063-11e9-93d7-c3f6e768cf92.png)

### Goals / use cases

- [ ] 
- [ ] 
- [ ]

**Comment by jendowns** [comment]
@clairek20 Would it be possible to add this "Share info" button to a new column in a given table?

**Comment by clairek20** [comment]
> @clairek20 Would it be possible to add this "Share info" button to a new column in a given table?

Hi @jendowns - sorry i'm not following. The button i want to add is an export button, i added it above as an example by adding a 'download' icon next to the 'add new' button. The export button would then export to a csv file. The npm package is export-to-excel.

**Comment by jendowns** [comment]
Thanks @clairek20! I see what you mean now...

In that case I think there are two existing routes you could go with this, if either of them fit your requirements:

### 1. Use a "batch action"

Take a look at this story here: https://ibm-security.carbondesignsystem.com/?path=/story/components-datatable--with-batch-actions
(Demo code is here: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/DataTable/stories/with-batch-actions.js#L67)

You can add a download button as a "batch action" that appears when you select rows of a `DataTable`, as pictured below:
![Screen Shot 2019-09-26 at 10 17 41 AM](https://user-images.githubusercontent.com/9057921/65701538-0dc7ab80-e047-11e9-95b7-5a370ed4e09f.png)

### 2. Use a "toolbar action" in a "toolbar menu"

There's a toolbar action that can be added that is effectively an overflow menu where you can add actions: https://ibm-security.carbondesignsystem.com/?path=/story/components-datatable--with-toolbar
(Demo code is here: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/DataTable/stories/with-toolbar.js#L43)

Here it is pictured below:
![Screen Shot 2019-09-26 at 10 23 10 AM](https://user-images.githubusercontent.com/9057921/65702092-081e9580-e048-11e9-8dfc-4d41a4346fa0.png)

_____

Would either of those options work for your situation?

**Comment by clairek20** [comment]
Hi @jendowns 

Thanks for the response. So would this change be made in carbon addons? That's essentially what i want. Rather than adding an export button to all the tables we have in clx individually, that we just add it to the carbon data table.

**Comment by clairek20** [comment]
> Hi @jendowns
> 
> Thanks for the response. So would this change be made in carbon addons? That's essentially what i want. Rather than adding an export button to all the tables we have in clx individually, that we just add it to the carbon data table.

@SimonFinney @jendowns any more thoughts on this?
