### ISSUE TITLE
Decorator icon loading state

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#107]
### Proposal

Sometimes a `Decorator` needs to be displayed *before* a score is available, due to a separate API call having to be made. 

While the current workaround is to set `noIcon={true}`, it would be a better user experience to indicate with a loading state of some kind that a score is coming and will ultimately be shown. The `noIcon` route does not properly convey that more information is coming.

Possibly:

```
<Decorator type="loading" />
```

A possible loading state in this case could be a small square icon, perhaps, than looks/behaves like a skeleton state animation with a shimmer?

**Comment by SimonFinney** [comment]
For sake of consistency with Carbon, I feel like we could revise this to `DecoratorSkeleton` - This seems like an appropriate use case and may require less effort.

**Comment by jendowns** [comment]
I like the idea of the revision, but the one thing is that this is a specific situation where the score is not known yet, but other information might be known. 🤔 We could have a skeleton component that shows partial info, if available, but generally a skeleton state is a first loading experience and not 100% the same as querying an API, for example, to get extra info?

**Comment by SimonFinney** [comment]
That makes sense to me. In this case, perhaps we follow Carbon's example by creating a `status` prop instead of introducing complexity to the current `type` prop implementation.

On another topic, are you aware if there are designs readily available to pick up this work?

**Comment by SimonFinney** [comment]
@techtolentino @jimmydyer - can you confirm if this is still a requirement and if there's designs currently available?

**Comment by jimmydyer** [comment]
@SimonFinney @techtolentino There isn't a design that was delivered and approved, but I quickly mocked these up today for how I would envision this to be implemented. Using the skeleton animation (gray boxes from the image below), there would need to be 2 different states of this component:

1. When everything is unknown (e.g. User views threat details and waits for indicators to load)
2. When only the risk score is unknown (e.g. API call to get risk score is taking longer to retrieve but the system has the other content, I'm sure there are other scenarios for this but it's what came to mind first.)

<img width="426" alt="ISC_Design_Library_sketch" src="https://user-images.githubusercontent.com/54411478/67590199-ffd97900-f71f-11e9-918c-020742019c6b.png">

I will be going on paternity leave soon, so I won't be able to contribute to much more discussions on this until I return. I'm tagging @cameroncalder and @petervachon on this issue just in case this isn't approved.
