### ISSUE TITLE
PanelV2 showing focus state

### ISSUE THREAD

**Issue by techtolentino** [carbon-design-system/ibm-security#133]
## Bug - The PanelV2 component is showing a focus state when clicking into its main content section.

**Expected behavior -**

There (maybe) should be no focus state(?)

**Actual behavior -**

Clicking into the panel puts the entire thing in focus, causing the outline to show

### Steps for reproducing

1. navigate to the [PanelV2 component](https://ibm-security.carbondesignsystem.com/?path=/story/patterns-panelv2--default)
2. click somewhere in the Panel Content
3. see the outline

#### PanelV2 focus state
<img width="1680" alt="Screen Shot 2019-10-08 at 9 11 15 AM" src="https://user-images.githubusercontent.com/6276074/66403140-ab0dd280-e9ab-11e9-9696-184f1de3cf49.png">

#### PanelV2 focus state with a lot of content
<img width="1680" alt="Screen Shot 2019-10-08 at 9 13 34 AM" src="https://user-images.githubusercontent.com/6276074/66403376-15bf0e00-e9ac-11e9-9fd5-4b028bbfba7f.png">

:pray:

**Comment by SimonFinney** [comment]
@techtolentino Thanks for raising! The focus state is required here so keyboard users are able to scroll if there is a large amount of content and no focusable element within the container.

It's not the prettiest solution, so we're open to suggestions here - @petervachon do we have guidance around interactions like this?

**Comment by techtolentino** [comment]
Oh thanks @SimonFinney - if it's already been part of a larger decision then I'm good.
