### ISSUE TITLE
An offering team developer can build third-party components specific to their suite of offerings

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#144]
#### Context

A potential requirement for managing multiple projects in a single workspace (https://lerna.js.org) has been identified to simplify the development workflow for other projects. This spike is to investigate the configuration, feasibility, and validity of making a shift in this workflow.

Migration and transition steps are available on Box.

##### Future consideration

- Naming conventions
- Unifying Storybooks
- Configuration consumed similar to Babel - Core is installed, and other packages as needed

#### Acceptance criteria

- [ ] An offering team can effectively build third-party components specific to their suite of offerings without it being tedious

##### A library can can

- [ ] leverage the same release process that is currently in place
- [ ] be automatically be added to the correct reviews (https://help.github.com/en/articles/about-code-owners)

**Comment by joshblack** [comment]
Love this stuff! Would love to figure out how we could share things like tooling for these kind of repo setups, too. On the carbon side, the hope is that this is what `@carbon/cli` is for. Under the hood, we use it for running ci checks, automating things like README generation and keeping package.json fields in the same order/in sync. We're trying to explore now what a custom build command would mean to help optimize build times such that only what has changed is recompiled. This also leads into build profiling as we start to instrument various parts of the project (bundle sizes, stats around react or styles)

In terms of package setup, I think we're also hoping to move towards this kind of setup:

![image](https://user-images.githubusercontent.com/3901764/67884984-c3898c80-fb14-11e9-9046-842f1d02f7a4.png)

And also exploring what kind of commands we could give to optimize for this. For example, having a `develop` command that would generate storybook config only for the component you pass in so you get minimal compile times as the codebase grows.

Let me know if you want to pair up on any of this stuff!

**Comment by areddon** [comment]
Based on your diagram above, it seems like you would like to have a package per component, with tooling shared between each package for build and CI, and then roll them up into a larger package that people consume, correct? 

That way, you can update components independently within the `@carbon/react` package.

This library would be able to create a separate package per component as well, and then roll up separate lists into various release packages such as `@carbon/ibm-security` and `@carbon/qradar`.

**Comment by joshblack** [comment]
Yup, exactly. There is some nuance with the component package stuff, it’s not necessarily that every component has to have a package, like accordion and accordion item both are individual packages. You could totally have a package like @carbon/accordion that has multiple components in it, as long as they are to be used within an accordion context. UI Shell would be another example.

And then, like you said, you roll them up into entrypoint packages that just re-export things in a friendly to use way.

**Comment by areddon** [comment]
Does the Carbon team have any timelines for switching to this setup and will the `@carbon/cli` package be consumable by this library?

I really like this setup, and hope that this is something @SimonFinney and @jendowns are also interested in working on with you and the Carbon team.

**Comment by joshblack** [comment]
@areddon most likely this is going to be a part of our v11 work to move towards scoped packages and use that as an opportunity to split out components and then combine them into dedicated packages. The big thing we'll want with scoped packages is that everything you need is in one installation, meaning no need for separate installs you can just install the one package and you're good to go.

For the `@carbon/cli` package, really I'd be interested in working on it whenever others are interested. Right now I'm exploring incremental rebuilds as part of a `build` command and would love to work alongside others on other parts of the CLI that would be useful/helpful.

**Comment by areddon** [comment]
It sounds like this can be adopted in multiple phases, the first of which being migrating to a monorepo, even if the only package is the library as it exists today. With that in place we can begin splitting out the components into dedicated packages.
