### ISSUE TITLE
Table columns move when switching between pages

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#150]
## Bug - 

For https://ibm-security.carbondesignsystem.com/?path=/story/components-datatablepagination--pagination-data-table, when user uses the page selector the column widths change on the table and so appear to "jump".  Browser independent.

**Expected behavior -**

Table column width is fixed so that they do not "jump" when going to other pages

**Actual behavior -**

When user uses the page selector the column widths change on the table and so appear to "jump"

### Steps for reproducing

1. Open https://ibm-security.carbondesignsystem.com/?path=/story/components-datatablepagination--pagination-data-table
2. Click on the page selector and select page 2
3. Observe the movement of the table columns while the pages are changing

### Screenshots

![image](https://user-images.githubusercontent.com/56437682/66651261-82474080-ec2a-11e9-9daf-6f32050520e0.png)

### Affected browsers

Browser independent

**Comment by jendowns** [comment]
As far as I know we don't do anything style-wise to manipulate these widths. There are a couple of rules defined by Carbon but they are mostly for setting the OverflowMenu width, etc. https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/data-table/_data-table-core.scss

I believe what you are seeing here is the browser doing its own calculations based on changing values in the table cells.

**Comment by sharon-oboyle** [comment]
OK, so it sounds like this is outside our control, if it's dependent on the browser calculations?

**Comment by sharon-oboyle** [comment]
Can we change the component to control this behaviour?

**Comment by jendowns** [comment]
@sharon-oboyle One possible solution for you is to add the following style rule:

```css
.bx--data-table {
    table-layout: fixed;
}
```

That should keep the columns consistent width as you switch between pages.

(Here's some info on that rule: https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout)

**Comment by sharon-oboyle** [comment]
Great thanks Jen I have opened a Jira issue to suggest this workaround.
