### ISSUE TITLE
Multiselect `SummaryCard`

### ISSUE THREAD

**Issue by sdignum** [carbon-design-system/ibm-security#153]
### Details

- **Application / team -** Design team
- **Needed by -** ASAP

### Proposal

For the `SummaryCard`, we need a way for this component to be multi-selectable and combined with the batch actions that comes with the `DataTable`. Screenshots below illustrate both states:

![image](https://user-images.githubusercontent.com/10590403/66763308-3b955880-ee6d-11e9-9111-0d860194fc46.png)
![image](https://user-images.githubusercontent.com/10590403/66763383-5c5dae00-ee6d-11e9-8679-cce847e3f01f.png)

#### A user

- [ ] can select a `SummaryCard` and begin a multiselect process
- [ ] can perform batch actions on the selected `SummaryCard`s (leveraging the `DataTable` batch actions where possible)

**Comment by jendowns** [comment]
Dependent on #128

**Comment by SimonFinney** [comment]
@sdignum - Can you confirm if this is still a requirement - have the designs progressed since?

**Comment by sdignum** [comment]
@SimonFinney yes it is still a requirement. Same designs.

**Comment by SimonFinney** [comment]
Thanks - we need to refine what the logic for this pattern would be if the logic is not handled on the application side

**Comment by sdignum** [comment]
yay!!! Thank you! 🙏
