### ISSUE TITLE
Value is unreadable after it is selected in Firefox

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#168]
## Bug - In Firefox, when you select an option in the Select component the option text becomes dark and unreadable until user clicks outside the component

**Expected behavior -**
When an option is selected, it is readable

**Actual behavior -**
After it is selected the option text becomes dark and unreadable until user clicks outside the component

### Steps for reproducing

1.  Click on https://pages.github.ibm.com/security/carbon-addons-security/branch/v2/?path=/story/components-select--default to display Select component
2.  Click on any option

<img width="662" alt="image" src="https://user-images.githubusercontent.com/56437682/67210628-4d4ca200-f411-11e9-9891-9087c734603b.png">

[Screen Recording 2019-10-21 at 15.02.28.mov.zip](https://github.com/carbon-design-system/ibm-security/files/3751212/Screen.Recording.2019-10-21.at.15.02.28.mov.zip)

### Affected browsers

- [ x]  Firefox 69.0 on Mac OS X 10.14

**Comment by jendowns** [comment]
FYI I fixed this in Carbon here: https://github.com/carbon-design-system/carbon/pull/4343

However due to release cycles and so forth, it may take some time for that update to get to you... so for now I can make that same override in this library.

**Comment by sharon-oboyle** [comment]
Oh brilliant!I had a feeling this had been discussed before but couldn't find the tracking issue.  thanks Jen!
