### ISSUE TITLE
Unable to change theme using `$security--theme` variable

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#170]
### Expected behavior

Considering this block of code in the themes file:

```scss
@import '@carbon/themes/scss/mixins';

/// Security theme.
/// @type Map<String, Color>
$security--theme: $carbon--theme--g100 !default;
```

I would expect to be able to change the Carbon theme directly in this file, like this:

```scss
$security--theme: $carbon--theme--white;
```

And see it reflected directly in the storybook when I run `yarn start`.

### Actual behavior

When I change the value of `$security--theme` to a different Carbon theme, the storybook still appears to use the `g100` theme. 

I imagine if the theme cannot be set in this library, then a consumer wouldn't be able to change the theme either. 🤔 

### Steps for reproducing

1. Change the theme set in `$security--theme` in the theme file to something noticeable like `$carbon--theme--g100` and then start the storybook dev build.

**Comment by SimonFinney** [comment]
Should be resolved with #137
