### ISSUE TITLE
Calendar icon for the end date is not working in DatePicker

### ISSUE THREAD

**Issue by shadab-ansari** [carbon-design-system/ibm-security#172]
## Bug - 

**Expected behavior -**

Clicking the calendar icon for End Date in DatePicker should open the calendar to change date

**Actual behavior -**

Clicking the calendar icon does not open the calendar

### Steps for reproducing

1.  Go to the storybook for DatePicker - https://ibm-security.carbondesignsystem.com/?path=/story/components-datepicker--single-with-calendar
2.  Set the beginning and end date
3.  Try to change end date by clicking on the calender icon for the end date

### Screenshots

![image](https://user-images.githubusercontent.com/56869622/67274096-b25ad300-f4b7-11e9-90d3-979fb53ec76b.png)

**Comment by jendowns** [comment]
This was fixed in the upstream library `carbon-components-react` and merged last week: https://github.com/carbon-design-system/carbon/pull/4325

We can expect to get this update when Carbon publishes a release that includes the fix, and then we update to that new release.

**Comment by SimonFinney** [comment]
This will be resolved with a Carbon update
