### ISSUE TITLE
Pagination refactor

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#186]
Currently the `Pagination` component from Carbon cannot deal with large numbers of pages, as the `Select` element for page selection will either overshoot the page and be very large, or in some cases when there are thoughts of pages for logs etc the `Select` will just crash the browser.

This PR is to track research into the best way to handle many, many pages (as in, thousands +) fed into the `Pagination` component.

**Comment by jendowns** [comment]
Closing out this PR to mark the end of this spike & the beginning of development work on the refactored `Pagination`

After speaking with Carbon & also a couple of our own devs, the best approach appears to be to keep the overall design of the current `Pagination` but refactor to use a "building blocks" approach. That way, in the event a large set of pages, a consumer can choose to lose out inner `Select` elements. And possibly add something else, like a `NumberInput` (note: a `NumberInput` may not be 100% feasible in the initial PR and may need to be a followup, to keep things reasonably sized).
