### ISSUE TITLE
Add "ghost danger" button variation

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#19]
### Proposal

We have a "ghost danger" button in the Tearsheet, but application teams are going to need the "ghost danger" button in other contexts as well. Therefore, it would be best if we broke it out into a reusable component.

**Comment by b3nk3** [comment]
@jendowns In order to do this neatly, the PR should be applied to the Button in Carbon Components React, then the relevant changes to be made on the Story of this repo. 

Would you agree?

**Comment by jendowns** [comment]
Hey @b3nk3 -- the immediate need is for a "ghost danger" button in this library. Of course, it can ultimately be added to Carbon proper and then we'd benefit, but that process can take longer due to the volume of feature requests that they need to review and add to their release plans.

Since this is something needed by our application teams, we can move a little faster in this case.

Take a look at what's been done to create a "large" button, for example: https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/Button/Button.js#L21
That size of button doesn't exist in Carbon, but we were still able to add it.

In the code above, we re-defined Carbon's `size` props and added a new size to the array of possible options to allow for a "large" button size. So we could also re-define their `kind` prop and add a new kind like "ghost--danger" or something like that.

**Comment by b3nk3** [comment]
Gotcha! Makes sense and I was going to choose a similar implementation method, but wanted to confirm before I went knee deep into a solution that does not suit your needs. 

Hoping to submit a PR soon :)

**Comment by jendowns** [comment]
Yeah sounds good! And after you get a PR in & merged, you could open an issue with Carbon asking that they absorb the update... it would be nice as well because then you'd be able to point to our storybook & the ghost danger variation as an example!
