### ISSUE TITLE
`Header` - Use `StringFormatter` for account name

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#191]
## `Header` - Use `StringFormatter` for account name

Currently the `Header` truncates once a certain amount of characters have been reached - the StringFormatter should be leveraged to provide a consistent tooltip for this experience.

<img width="311" alt="Account name" src="https://user-images.githubusercontent.com/3846874/68320355-ba219680-00b7-11ea-9eb5-d571476b0c41.png">

**Comment by jendowns** [comment]
Marking as defect since the truncated text is required to have a tooltip for a11y purposes.
