### ISSUE TITLE
Font-size broke on headers on Homepage

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-security#20]
## So much font-size
 
It looks like you guys are using an SVG for your homepage. Why not just use H2's?

**Comment by jendowns** [comment]
Hey @sstrubberg! The screenshot above is from our internal-only site, and the font-size design decision + the execution of it were separate from this library & completed by different folks. 

I'll send you a link to the internal repo on Slack, if you wanted to connect those folks on GHE.
