### ISSUE TITLE
Header popover title breaks words

### ISSUE THREAD

**Issue by j1mie** [carbon-design-system/ibm-security#247]
The title on the header popover is currently set to `break-all` which can result in broken names.

**Expected behavior**

- Styles avoid breaking names in the middle of words

**Actual behavior -**

- Names are broken in the middle of words

### Steps for reproducing

1.  Visit https://ibm-security.carbondesignsystem.com/?path=/story/patterns-header--with-active-user
2.  Click on the knobs tab
3.  Type in:

```
{
  "image_url": null,
  "name": {
    "first_name": "Firstname",
    "surname": "Lastname"
  }
}
```

### Screenshots

<img width="325" alt="Screenshot 2019-12-04 at 12 16 42" src="https://user-images.githubusercontent.com/12685163/70141913-f41e9200-168f-11ea-9158-97c461e573e2.png">

**Comment by SimonFinney** [comment]
@petervachon Can you confirm the desired behavior? I'm assuming we break by individual words and not by incomplete words

**Comment by petervachon** [comment]
Yes, let's go with word-break: break-word
