### ISSUE TITLE
Add `ContextMenu` component

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#25]
### Context

* Investigate `ContextMenu` feasibility, including accessibility concerns.
* Add accessible `ContextMenu` component

**Comment by jendowns** [comment]
The biggest issue I see with the `ContextMenu` as is currently implemented is that there is no way to  access or navigate the menu with a keyboard. I think there is a way make it keyboard accessible with a few changes, however.

Specifically DAP flags the following:

> Widget with role of button must have at least one tabbable element.

I'm going to update this issue to a task to add an accessible variation of the `ContextMenu` to this library 👍

**Comment by diego-codes** [comment]
Chiming in with some concerns I've had about context menus that are rendered via right-clicks...

> There are some improvements we can make to the context menu is rendered, because:
> - context menu switches are not accessible to keyboard-only or mobile users.
> - context menu switches are not clearly identifiable (there are not indicators of what UI elements has a context menu)
> - right-click context menu rendering functionality hijacks native OS functionality which can be unexpected and unpleasant to the user

From my perspective, the only way to have a successful `ContextMenu` component is to have visible indicators on elements that have a context menu and that it can be called to render via a simple click (no right-clicking or hovering).

**Comment by jendowns** [comment]
Thank you @diego-codes! I like your idea of having a visible indicators on elements that have a context menu, and also using something other than right-click.

With the visible indicators in particular, I feel like this is probably something that should be revisited on the design-side. 🤔 

@SimonFinney how would you like to proceed with bringing these suggestions back to Design?

(For now I'm going to un-assign myself. We don't really have a status label that fits this, except for maybe `question` so I'll add that label as well)

**Comment by SimonFinney** [comment]
Thanks for the investigation and insight @diego-codes and @jendowns !

I think we can defer pursuing the current implementation until requested by other use cases, unless we have a resource to pursue a redesign - @petervachon can you confirm priority?

**Comment by SimonFinney** [comment]
@diego-codes I heard mention of this during last week's playback and thought I'd revive the conversation - what's the current thought on sharing this across offerings?
