### ISSUE TITLE
User Account toggle, does not close on the second click (FIREFOX ISSUE)

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#274]
The user account toggle on the upper right hand side (with your first name initial), opens when you click on it once, but when you click on it again it should close. However it opens once more and on the third try it closes.

Steps to Reproduce
Open firefox 
Go to carbon addons security -> shell -> click on notifications or user profile
Once open try to close it again with click on the icon.

Expected Outcome
The modal should close on the second click on the icon.

Actual Outcome
Modal opens again on the second click and retreats on the 3rd one.

Defect Impact
Inconsistent button behaviour. (As in sometimes it just keeps opening for every consecutive click after the first)

![image](https://user-images.githubusercontent.com/55839633/71001741-ce54ac80-20d5-11ea-8fda-599a06c6d243.png)

**Comment by clairek20** [comment]
Hi @SimonFinney , @jendowns 

Is there any update on this one? 

Thanks in advance, Claire.

**Comment by jendowns** [comment]
Hey @clairek20 sorry for the delay getting back to you -- no progress yet, unfortunately! 😭

**Comment by SimonFinney** [comment]
@clairek20 This will be resolved with the `Shell` refactor work - https://deploy-preview-285--ibm-security.netlify.com/?path=/story/patterns-unstable-shell--notifications

**Comment by SimonFinney** [comment]
Closing, as per confirmation during sprint exit

**Comment by joemc11** [comment]
reopening and discussed @jendowns.  Issue ocurrs in version 1.29.0.   https://ibm-security.carbondesignsystem.com/?path=/story/patterns-shell-security--default. Click the SU icon in top right corner in firefox browser and click again and the dialog does not close.  In chrome the dialog closes okay.

**Comment by sstewart199** [comment]
@SimonFinney I know this item has been closed but is there any update on this? Still the same issue on Firefox only.
