### ISSUE TITLE
Dropdown menus very short when a lot more vertical space is available on UI

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#275]
Description

On alot of dropdowns, they expand vertically very little, only displaying 3 items at a time, and an internal scroll bar. Dropdown could increase in size vertically, making easier for user to select data sources, especially when many configurations available for selection.

Steps to Reproduce

Go to Data Explorer
Click on Data Sources dropdown
Observe dropdown is very small, displaying only 3 Config names at a time.
AND
Go to Cases, open a case
Click on Activity and click on filters dropdown.
Observe dropdown is very small, displaying only 3 names at a time.
 

Expected Outcome

Dropdown could increase in size vertically, making easier for user to select data sources, especially when many configurations available for selection.

Actual Outcome

Dropdown is very small.

Impact

User has to scroll a lot inside dropdown in order to select different configurations

 
Time seen

November 14th, 2019

![image](https://user-images.githubusercontent.com/55839633/71007248-969e3280-20de-11ea-8969-8cd2fb9d9cbb.png)

![image](https://user-images.githubusercontent.com/55839633/71007295-aae22f80-20de-11ea-9c99-f2c2ab97475b.png)

**Comment by clairek20** [comment]
Was raised initially in https://github.ibm.com/security-secops/IBM-Security-Cloud/issues/3567#issuecomment-16028128.

**Comment by jendowns** [comment]
@SimonFinney @clairek20 Looking into this -- I think it would be more appropriate for consumers to adjust this menu height, as needed.

Right now that style rule is `max-height: 9.75rem` applied to a single class for the menu, `.bx--list-box__menu` --
![Screen Shot 2019-12-19 at 10 39 19 AM](https://user-images.githubusercontent.com/9057921/71191454-11d12700-224c-11ea-9130-6bc1ba1b5b59.png)

I think it would be reasonable to ask consumers, on an as-needed basis, to target that `.bx--list-box__menu` class & increase the `max-height`. 

But I don't think it's a good idea for this library to change the `max-height`, which is set in the upstream `carbon-components` library.

**Comment by jendowns** [comment]
Hey @clairek20! I was wondering what you thought about my comment above? https://github.com/carbon-design-system/ibm-security/issues/275#issuecomment-567567425

**Comment by clairek20** [comment]
Thanks for the response @jendowns 

Sounds good, i will let the team know! Thanks a million!
