### ISSUE TITLE
'PanelV2' refactor initial focus when using focusTrap

### ISSUE THREAD

**Issue by ShayMurnin** [carbon-design-system/ibm-security#276]
## Request
Hello team! We have a use case on Falcon where the `subtitle` prop for `PanelV2` will be a component that is wrapped in a `Tooltip`.

We need `PanelV2` to trap focus. But we've run into an issue when `focusTrap={true}` (as it is as by default).

When the panel opens, initial focus is applied to the first focusable element within the panel. I'd imagine in most cases this is the close button as `title` and `subtitle` are usually just labels.  In our case - it applies focus to the `Tooltip` as it's the first focusable element (see below).

![with-focus-trap](https://user-images.githubusercontent.com/15728451/71012892-b2f29d00-20e7-11ea-94ea-cd845ccb8f4f.gif)

I guess this is expected behaviour for keyboard users. It just seems a bit jarring with the `Tooltip` component specifically - when compared to focusing on the close button (below, after tweaking).

![without-focus-trap](https://user-images.githubusercontent.com/15728451/71011746-e3d1d280-20e5-11ea-8a2d-c01d61dfac4a.gif)

### Details

- **Application / team -** QRadar / Spectre
- **Work item -** N/A
- **Needed by -** N/A

### Proposal
In terms of expected behaviour, I don't think we'd be wise to skip the subtitle and initially focus the close button - as the user would need to tab backwards to read the subtitle, _then_ tab forward (back over the close button) to read the panel content.

My thought here was that we could just let html and css take care of it by:
1. Moving the close `<IconButton/>` to be the first child of the `<header/>` flex container
2. Add `flex-direction: row-reverse` to `<header/>`

I've implemented this approach with `Tooltip` as subtitle using storybook (below) and is working as expected.

|As-is   	|With changes  	|
|---	|---	|
![before-change](https://user-images.githubusercontent.com/15728451/71015040-dcf98e80-20ea-11ea-9a98-e260b1ff6471.gif) | ![after-change](https://user-images.githubusercontent.com/15728451/71015054-e4b93300-20ea-11ea-9377-f73feee46b7f.gif)

Lemme know what you guys think 🙂

**Comment by SimonFinney** [comment]
@ShayMurnin Thanks for raising - It seems like the ask is to make the 'close' button the first element in the markup of the `Panel` to avoid focus trap ordering issues. I don't see any harm with this at a glance!

@jendowns Would you mind providing input as you built this component originally? Please and ta!

**Comment by jendowns** [comment]
Thank you @ShayMurnin -- you recommendation makes sense & I don't see any harm in reordering the header & add then applying a row-reverse flex rule. I'll propose that fix shortly 👍
