### ISSUE TITLE
End-Users Require Horizontal Navigation

### ISSUE THREAD

**Issue by Acts7** [carbon-design-system/ibm-security#29]
## Request - 
The ask is for a horizontal navigation for end-user's frequently used nav items.

### Details

- **Application / team -** User Self Care
- **Work item -** Cloud Identity
- **Needed by -** September 15, 2019 -- if possible

### Proposal

The target audience for our product are end-users who require immediate access to a handful of navigational items. The end-user navigates back and forth between these select nav items several times each session. To provide the best possible user-experience, we need to present these navigational components up front rather than hidden behind the hamburger menu.

![]()
![image](https://user-images.githubusercontent.com/152856/63608677-2ef63180-c59b-11e9-9329-6c1322d4a556.png)

There's a need to differentiate between both Carbon and Security's shells in Storybook to avoid consumer confusion.

### Goals / use cases

- [ ] 
- [ ] 
- [ ]

**Comment by SimonFinney** [comment]
Tagging @petervachon for visibility

**Comment by cassiesharp** [comment]
This is the component we need added to Security Carbon addons:
https://www.carbondesignsystem.com/components/UI-shell-header/code

Header with actions and nav
- Horizontal nav
- Menu item dropdown menu
- Icon actions

![image](https://user-images.githubusercontent.com/22551396/65984651-d8a3ca80-e445-11e9-8cb0-d92d8ab05642.png) @SimonFinney

**Comment by SimonFinney** [comment]
Thanks @cassiesharp ! We can bring that directly through from Carbon.

In reviewing some designs, there may be some additional work required to abstract the 'User Profile' work on the right-hand side, but we can start with the header for now.

**Comment by SimonFinney** [comment]
@cassiesharp Can you confirm the need still exists for this?

**Comment by cassiesharp** [comment]
Yes, we do need it @SimonFinney
