### ISSUE TITLE
Side panel automatically focuses on close button when opened

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-security#293]
## Bug - When the side panel is opened the focus is automatically put on the close button
![image](https://user-images.githubusercontent.com/55839633/71816174-b095ba00-3079-11ea-8d19-aaaf27e7db9f.png)

**Expected behavior -**
Shouldn't be a visible/obvious focus when opened

**Actual behavior -**
Focus is on the close button

### Steps for reproducing

Go to panel -> click on button -> panel opens with focus on the close button

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by clairek20** [comment]
There's also an issue for one of the teams screens where the panel would look better of there was a bigger width:

**Comment by jendowns** [comment]
hey @clairek20! This is an accessibility requirement, similar to the Carbon's `Modal` -- http://react.carbondesignsystem.com/?path=/story/modal--default

With regards to the width of the `Panel`, there are design standards here with regards to keeping things looking consistent across the platform. @cameroncalder or @petervachon would be good resources to talk to about that.

**Comment by clairek20** [comment]
Perfect thanks a million @jendowns!

**Comment by petervachon** [comment]
In regards to the width, we should not change it to match/hide the overlap of content. If you use the panel V2, it comes with an overlay that masks the content below to remove such a harsh collision of content and focus the user on the panel itself. https://ibm-security.carbondesignsystem.com/?path=/story/patterns-panelv2--default
