### ISSUE TITLE
Storybook source code, not always immediately available

### ISSUE THREAD

**Issue by dan-cooke** [carbon-design-system/ibm-security#304]
## Request - 
Just a minor annoyance, (maybe I'm missing something) - but when quickly prototyping an app . l like to go onto storybook, copy and paste the storybook code to get my component up and running instantly.

Usually its enough to just open the "Show More" and grab the source code from there - but sometimes a particular variation may not show the correct source code.

For example:

Here I've selected `DataTable - with expansion` - it would be _super_ useful to have this Show More , display the source for this exact variation.

Instead its showing the source for some other variation

<img width="1292" alt="Screenshot 2020-01-13 at 13 49 32" src="https://user-images.githubusercontent.com/22816887/72260825-8d37b580-360b-11ea-85c0-d4c2f30d5337.png">

## Workaround
At this point usually I just have to open the project on github and find the storybook files manually

Keep up the great work everyone! V2 is wonderful!

**Comment by jendowns** [comment]
Hey @dan-cooke -- unfortunately Storybook's `info` plugin does not display render props correctly. (In this case, `render={function noRefCheck(){}}`)

Our `DataTable` stories in this case are copied from Carbon so you can see that their storybook experiences the same issue: http://react.carbondesignsystem.com/?path=/story/datatable--with-expansion

**Comment by dan-cooke** [comment]
Oh I wondered what was going on with that. 

Makes a lot of sense now! 

Thanks
