### ISSUE TITLE
Support for other React routers in Nav

### ISSUE THREAD

**Issue by eknowles** [carbon-design-system/ibm-security#31]
### Proposal

Currently can not use Shell/Header/Nav with custom routers like [react-router](https://reacttraining.com/react-router/) or [@reach/router](https://reach.tech/router) due to config in Shell not allowing for custom Link component

### Goals / use cases

- [ ] Use IBM Security Shell in a React SPA

**Comment by SimonFinney** [comment]
@eknowles Thanks for raising, and welcome!

Can you provide some additional context around this request? How and where are you trying to use this component?

**Comment by SimonFinney** [comment]
Closing in favour of future work for making the `Shell` more consumable
