### ISSUE TITLE
DataTable.TableOverflowCell remains visible while the table row is hidden

### ISSUE THREAD

**Issue by hlyang397** [carbon-design-system/ibm-security#316]
## Bug
1. A DataTable is located below a <div/> with fixed position (ex: banner)
2. Scroll table down, some rows will be hidden under banner.
3. The TableOverflowCell remains visible

**Expected behavior -**
The TableOverflowCell should become invisible when table row is hidden.
![Expected](https://user-images.githubusercontent.com/59426533/72535331-57b4f580-38b3-11ea-8fa4-123835dfdfab.png)

**Actual behavior -**
The TableOverflowCell remains visible when table row is hidden.
![Actual](https://user-images.githubusercontent.com/59426533/72535306-4966d980-38b3-11ea-88bf-c36996c481c5.png)

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  
2.  
3.  

#### 

![]()

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -** 1.10.1-prerelease.1

**Comment by jendowns** [comment]
@hlyang397 could you provide a simplified example in CodeSandbox, illustrating this issue? https://codesandbox.io/s/codesandbox-nmmqp

**Comment by hlyang397** [comment]
@jendowns Here is the example. 
[codesandbox.zip](https://github.com/carbon-design-system/ibm-security/files/4080199/codesandbox.zip)

Please let me know if you need anything else, thanks.

**Comment by jendowns** [comment]
Thank you @hlyang397 I was hoping for a link though, rather than a `.zip`, if that's possible? 😅 If you edit the CodeSandbox link I posted above and fork/save it, then a new unique link will be generated that you should be able to share directly.

**Comment by hlyang397** [comment]
Hi @jendowns ,
https://codesandbox.io/s/codesandbox-u0x1j
