### ISSUE TITLE
how to change themes for components in react

### ISSUE THREAD

**Issue by sanyam53** [carbon-design-system/ibm-security#317]
i tried importing import "@carbon/ibm-security/css/index.min.css" (Sass); but it's not working, how to change thmes for component like i want to use Cool gray 10 for all carbon components i am using in my react app

**Comment by SimonFinney** [comment]
Hi @sanyam53 - Please review theming documentation at https://github.com/carbon-design-system/ibm-security/tree/dev/docs/themes

**Comment by SimonFinney** [comment]
Deferring to Slack conversation
