### ISSUE TITLE
Scroll Gradient is wrong color in Safari

### ISSUE THREAD

**Issue by rmccaskill** [carbon-design-system/ibm-security#328]
## Bug - 
When looking at the FilterPanel component when Safari, the gradients are grey, not white. 

**Expected behavior -**
Text should like like it's fading away' under the gradient in the Cool Gray 10 theme.
Working (Chrome)
![image](https://user-images.githubusercontent.com/1984709/73092135-605c8b80-3eb2-11ea-8f47-df46778000cf.png)

**Actual behavior -**
Text appears behind grey gradient
![image](https://user-images.githubusercontent.com/1984709/73092169-74a08880-3eb2-11ea-8f33-58426bf9fea9.png)

Happens with horizontal scrolling also. 

### Steps for reproducing

1.  Open Safari on OSX (or iOS)
2.  Navigate to https://ibm-security.carbondesignsystem.com/?path=/story/components-scrollgradient--vertical-scrolling

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ] Safari 13.0.3 on Mac OSX 10

**Comment by jendowns** [comment]
Thank you @rmccaskill -- this may be related to an issue that was brought up in the Carbon codebase with their `CodeSnippet` gradient -- https://github.com/carbon-design-system/carbon/pull/4859 In that case, the `transparent` keyword being used is treated differently in Safari.

I can look into this 👍
