### ISSUE TITLE
Search Component - control on search input field close initially 

### ISSUE THREAD

**Issue by geechia** [carbon-design-system/ibm-security#343]
### Details

- **Application / team -**  Cloud Identity webui / Design team
- **Needed by -** ASAP

### Proposal

The search input field is in close state initially,   a new property to allow  to programmatically set close initially,  or set search input field stays open when there is search term in the field.  
Similar support in  DataTable.TableToolbarSearch component with the "persistent" property. A 

![image](https://user-images.githubusercontent.com/10051308/73680074-9f949480-4689-11ea-8468-303df88bfe8f.png)

![]()

### Goals / use cases

- [ ] 
- [ ] 
- [ ]

**Comment by SimonFinney** [comment]
To bring in `DataTableToolbar` into `SummaryCardContainer`

**Comment by geechia** [comment]
Simon,  
The search requirements are:  
1. able to control the open and close state of the search input field ->  TableToolbarSearch support this.
2. able to set the value/initial value -> Search component support this,  TableToolbarSearch does not

**Comment by SimonFinney** [comment]
@geechia Can you confirm which component you're attempting to use for this? The `Search` component?

**Comment by geechia** [comment]
I used the <Search> component right now, because it allows to set initial value.  
If you want to bring in TableToolbarSearch for the cards, then please add the support to set initial value.
Either component for the search functionality is fine as long as the component support both search requirements stated above.
Thanks!

**Comment by geechia** [comment]
Correction on previous comment: I used the Search component right now.

**Comment by SimonFinney** [comment]
@geechia Is this still a requirement?
