### ISSUE TITLE
Question about demos

### ISSUE THREAD

**Issue by jshuadvd** [carbon-design-system/ibm-security#353]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-ibm-security`

## Summary
Hello, just a quick question as to where I can actually see some of the live demos of the products in the gallery of the docs page located [here](https://www.ibm.com/design/language/gallery/) like [this](https://www.ibm.com/design/language/3848c9434118d5b71e65ab6521b6d1f4/IBM_Security_Cloud_Prototype.gif), and [this](https://www.ibm.com/design/language/static/IBM_Security_Threat-Intel-Dash-a98137b2df330b6ea2fe7dba913cc699.mp4), as well as the images [here](https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#alignments) in the image above the linked section?

Adding Images here for reference as well.

Any help would be appreciated. 

![Image_5](https://user-images.githubusercontent.com/7577457/73985907-3d3dcd00-48f1-11ea-83a7-e0ed1d7510e3.jpg)

![Image_8](https://user-images.githubusercontent.com/7577457/73985966-5f374f80-48f1-11ea-9f43-80639ba073d4.jpg)

![IBM_Watson_Health](https://user-images.githubusercontent.com/7577457/73985980-652d3080-48f1-11ea-8c29-8addaefcfd16.jpg)

![2_1-1_ProductandWeb1](https://user-images.githubusercontent.com/7577457/73985997-724a1f80-48f1-11ea-856c-dd71391bd9d9.png)

![ThreatLandscape-Default](https://user-images.githubusercontent.com/7577457/73986001-74ac7980-48f1-11ea-96d2-4fc0f3ac428b.png)

**Comment by SimonFinney** [comment]
Hi @jshuadvd ! See https://www.ibm.com/products/cloud-pak-for-security for further information - thanks!

**Comment by jshuadvd** [comment]
Hi @SimonFinney thank you for the quick response. I looked into it and it seems that I need to schedule a call with a specialist to purchase a service. AS a developer this is frustrating. I (and I'm sure others) would like to work with a demo of  this in order to see how things are laid out as well as functionality. Especially if using the Security Components package to develop applications. 

Would you happen to have a current demo? All of the ones discuss or that are available for a preview on the link you share definitely do not look like any of the images above. Please help. Thanks.

**Comment by SimonFinney** [comment]
@jshuadvd Unfortunately as these are enterprise solutions, this is typically how access to the offering is provided.

If you would like further usage information on the individual components themselves, please use our Storybook environment - https://ibm-security.carbondesignsystem.com
