### ISSUE TITLE
Bug - Decorator story is displaying HTML entities instead of escaped characters

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#356]
**Expected behavior -**
The `Decorator` should display the intended HTML entity character instead of its code.

**Actual behavior -**
The `Decorator` component is not displaying escaped characters properly. For example, if one provides:  
```
<Decorator value="\"C:\\Program Files\\Confer\\RepMgr.exe\"" />
``` 
as the value of a decorator, 
```
&quot;C:\\Program Files\\Confer\\RepMgr.exe&quot;
``` 
is displayed.

### Steps for reproducing

1.  Go to the decorator preview in Storybook
2.  Paste in `"C:\\Program Files\\Confer\\RepMgr.exe"` in the value knob for the preview
3.  Notice the odd formatting of the string.

#### Input
![image](https://user-images.githubusercontent.com/5973294/74051565-d2969b00-499d-11ea-82d8-030037606678.png)

#### Output
![image](https://user-images.githubusercontent.com/5973294/74051540-c4487f00-499d-11ea-9874-7a47f019dbaf.png)

**Comment by jendowns** [comment]
I just wanted to point out that this is a feature of a storybook knobs -- they appear to have `escapeHTML: true` by default, which causes this behavior for knobs: https://github.com/storybookjs/storybook/tree/next/addons/knobs#withknobs-options

But I think it would be acceptable to set this option to `false` for the `Decorator` & `DataDecorator` 🤔 I'll open a PR for that so we can all discuss.

**Comment by diego-codes** [comment]
Oh, you're totally right! If it's knobs behavior, I'm fine with it. I didn't realize that was why, but I'd prefer to keep storybook secure by escaping HTML.
