### ISSUE TITLE
Request: Update version of the React transition animation dependency

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#401]
### Details

- **Application / team -** Data explorer

### Proposal
Our UI and test console logs are littered with the following React warning which is coming from components in this package:

![image](https://user-images.githubusercontent.com/5973294/75297305-1fc79900-57f5-11ea-8571-d2d9b3eba6b5.png)

This request is to get this package to upgrade its version of its React transition animation library to one that does not cause this warning to appear. According to the [`react-addons-css-transition-group` npm page](https://www.npmjs.com/package/react-addons-css-transition-group) this library has not been updated in 2 years. It recommends that users use [`react-transition-group`](https://github.com/reactjs/react-transition-group) instead. The recommended library should not have the same warning issues.

### Goals / use cases

- [ ] Clear up the consoles of consuming applications
- [ ] Move to a React transition animation library that is actively maintained

**Comment by SimonFinney** [comment]
Thanks @diego-codes ! I believe have a similar issue open for this ( https://github.com/carbon-design-system/ibm-security/issues/60 ), but last I checked, it requires significant rework on our end (and potentially consumers) and we have been unable to dedicate resource to it just yet.

**Comment by diego-codes** [comment]
Gotcha. I believe v1.x of `react-transition-group` is supposed to be a 1:1 transition from the old package.

**Comment by jendowns** [comment]
It might be worthwhile to investigate this again with fresh eyes? When I first opened #60 last year, I did an initial investigation and found that it wasn't quite 1:1. *However* it's been so long, I can't help but think that it might be easier now?

**Comment by SimonFinney** [comment]
Closing in favor of reviving https://github.com/carbon-design-system/ibm-security/issues/60
