### ISSUE TITLE
`Toolbar` external link icon shrinks when a large amount of text is provided

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#407]
## Bug - `Toolbar` external link icon shrinks when a large amount of text is provided

**Expected behavior -**

The toolbar external link icon should maintain aspect ratio when a large amount of text is provided.

**Actual behavior -**

The toolbar external link icon shrinks when a large amount of text is provided.

### Screenshots

![External link.png](https://images.zenhubusercontent.com/5879609351aa2c305772123d/a57d760b-1ee5-4285-b86a-a1ee059565e7)

**Comment by jendowns** [comment]
FYI this looks like the issue is with the underlying `NavItem` 🕵️‍♀️
