### ISSUE TITLE
Ability to pass in your own <Link> component when your component has ability of navigation

### ISSUE THREAD

**Issue by Deriohig** [carbon-design-system/ibm-security#416]
### Details

- **Application / team -** Insights
- **Work item -** Connections experience, contact me for more details
- **Needed by -** Its not required, just nice to have

### Proposal

Anywhere there is a href we should be able to navigate using a third party framework's native routing. Currently im just wrapping things like the `<Card>` in the `<Link>` element (Next.js) and then styling the hover effect manually. It would be cool if this came out the box from you guys, but understand that it would require a lot of changes. 

![]()
![image](https://user-images.githubusercontent.com/7848154/75781757-b5af7680-5d55-11ea-89f6-30b0a1a1ca2b.png)

## Acceptance criteria

- [ ] The `Card` can accept elements from third-party frameworks to use in place of the `a` tag

**Comment by SimonFinney** [comment]
@Deriohig Are there any components in particular you'd like us to focus our efforts on?

**Comment by Deriohig** [comment]
@SimonFinney The Card component, the breadcrumb, and shell are the main navigation elements for us really. The way that the `<Link>` works in next is that you wrap your anchor in it. 

```
<Link href="/about">
        <a>About</a>
</Link>
```

**Comment by jendowns** [comment]
@Deriohig With regards to the `Breadcrumb`, if you leave out the `href` prop on `BreadcrumbItem`, it will just render as a wrapper `li` & you can pass in a child anchor (or routing element, as is your need).

Our storybook demo doesn't really show this but Carbon's does: https://react.carbondesignsystem.com/?path=/story/breadcrumb--current-page

Take a look at the "story" tab at the bottom. The first `BreadcrumbItem` demonstrates this.

I will update our own story to properly demonstrate this API. 👍
