### ISSUE TITLE
a11y tests - create utility for tests to minimize code duplication

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#427]
## Proposal

From @diego-codes  --

https://github.com/carbon-design-system/ibm-security/pull/375#discussion_r389133806
> Just a suggestion, it might be useful to create a [custom renderer](https://testing-library.com/docs/react-testing-library/setup#custom-render) for a11y tests that handle the creation of the main element and setting it as a container.

https://github.com/carbon-design-system/ibm-security/pull/375#discussion_r389135388
> Do all of Axe / DAP tests have the same expect statements? What if this whole test function is converted into a utility that reduces the code duplication? Something like: `testA11y(<FilterPanelAccordion title="test accordion title" />);`

### Acceptance criteria

- [ ] Custom renderer that handles the creation of the main element and setting it as a container
- [ ] Utility test that reduces code overhead for axe and DAP test declarations
- [ ] Existing accessibility tests are refactored to use proposed implementation

**Comment by diego-codes** [comment]
> There may be situations where this isn't necessary, like if we end up having a component with its own sufficient landmarks. (Haven't come across one yet. For some reason, I imagine the Shell would apply here?)

In those cases, you might not use the custom renderer and use the normal RTL renderer and that's totally fine IMO. There are many ways the utilities can be conceptualized and it depends on how much flexibility or rigidity you require. Here are a few of the multiple possible implementations.

**Fully contained test:**
```jsx

const testA11y = (testId, renderFn) => 
  test(`should have no Axe or DAP violations ${testId}` , async () => {
    renderFn();
    await expect(document.body).toHaveNoAxeViolations();
    await expect(document.body).toHaveNoDAPViolations(testId);
  });

// Test component that already has a landmark 
testA11y('Shell', () => render(<Shell {{...props}} />)); 

// Test component that needs to be rendered in a landmark
testA11y('single FilterPanelAccordion', () => renderInA11yLandmark(<FilterPanelAccordion {{...props}} />)); 
```

**Separate assertion:**
```jsx

const assertA11y = async (Component) => {
  await expect(document.body).toHaveNoAxeViolations();
  await expect(document.body).toHaveNoDAPViolations(Component.displayName);
}

// Test component that already has a landmark 
test('should have no Axe or DAP violations' , async () => {
  render(<Shell {{...props}} />);
  assertA11y(Shell);
});

// Test component that needs to be rendered in a landmark
test('should have no Axe or DAP violations' , async () => {
  renderInA11yLandmark(<FilterPanelAccordion {{...props}} />)
  assertA11y(FilterPanelAccordion);
});
```


> Less of a reason, but -- this seems like a good way to make people remember the landmark requirements. 😆

What is the value of making people remember the landmark requirement in a11y tests?

**Comment by SimonFinney** [comment]
Nice! I'm glad we're doing this!
