### ISSUE TITLE
Bug: Theme tokens are vars even when enable-css-custom-properties feature flag is disabled

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#463]
⚠️ This bug is high-priority for us.

**Expected behavior -**
When the `enable-css-custom-properties` feature flag is set to `false`, no SCSS variable should resolve to a CSS variable. For example, `$ui-background` should resolve to `#161616` instead of `var(--ui-background, #161616)`. This expected behavior is important because we need to be able to do color manipulations in SCSS which require the actual hex value.

**Actual behavior -**
When the `enable-css-custom-properties` feature flag is set to `false`, all theme token variables resolve to a CSS variable. The problem comes for this themes map transformation: https://github.com/carbon-design-system/ibm-security/blob/d41ef379c6339d1b8ad5588349aa9c0ae2b58ef8/src/globals/theme/_index.scss#L24-L32

### Steps for reproducing
I do not have a functioning sandbox to demonstrate the actual behavior because the SCSS imports break for `@carbon/ibm-security` in code sandbox. However, this is the expected behavior directly through Carbon:
[CodeSandbox](https://codesandbox.io/s/carbon-theme-tokens-scss-test-e8e0g)

Here is how to probably best replicate the actual behavior: 
1.  Run Storybook
2.  In any of the component scss files add the following debug statements:
    ```
    @debug $feature-flags;
    @debug $ui-background;
    ```
3.  Check the terminal for the debug output.
4. Notice that the `enable-css-custom-properties` feature flag is set to `false`, by default.
5. Notice that the `$ui-background` is `var(--ui-background, #161616)`.

### Screenshots

![image](https://user-images.githubusercontent.com/5973294/78057954-3067b380-734d-11ea-8bb2-bd993293f4e0.png)

**Comment by diego-codes** [comment]
I'm not sure what all needs to be done for themes to work in `@carbon/ibm-security`, but replacing the theme variables that belong to Carbon seems to be heavy-handed and unnecessary.

**Comment by SimonFinney** [comment]
Thanks for raising @diego-codes ! I believe this is a duplicate of #415, wherein we need to account for a flag for consumers to toggle this off.

By default, we have enabled CSS custom properties to deliver custom themes (cool gray 10 which has additional design requirements beyond the standard token system) for consumers to readily switch between via classes if they're consuming solely the output CSS, versus through recompilation which requires SCSS to adopt.

The redefinition of variables was a necessary evil at the time of implementation, and needs to be reconsidered in a later release to adopt Carbon's ability to prefix these values and remove some of the overhead currently employed - https://github.com/carbon-design-system/carbon/blob/master/packages/themes/scss/_mixins.scss#L24
