### ISSUE TITLE
Custom icon for Decorator component

### ISSUE THREAD

**Issue by dan-cooke** [carbon-design-system/ibm-security#470]
### Proposal
I was wondefing if there are any plans to allow us to specify a custom icon for the [decorator](https://ibm-security.carbondesignsystem.com/?path=/story/components-decorator--default).

In our UI we do not imediately know the `score` prop, as we have to reach out to external services to get this value. So we would like to display a loading indicator while we are waiting for this request.

**Comment by SimonFinney** [comment]
Duplicate of #107
