### ISSUE TITLE
Shell at the right constantly highlighted action button even when Users are not selecting or clicking on the specific button

### ISSUE THREAD

**Issue by chrismichaelmurphy** [carbon-design-system/ibm-security#472]
## Bug - 

**Expected behavior -**

Just to see one tool-tip 

**Actual behavior -**

Seeing two tool-tips

### Steps for reproducing

1. Click on shell sidebar
2. Click on Settings to open
3. Click on Settings to close
4. Now hover over support and you will see 2 tooltips

[CodeSandbox](https://codesandbox.io/s/)

#### 

![2020-04-03_14-46](https://user-images.githubusercontent.com/4655548/78371073-644a0f80-75bf-11ea-9075-a64efd60ccee.png)

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
I believe this is working as intended, as the tooltip should display on hover and keyboard focus

**Comment by SimonFinney** [comment]
@cameroncalder / @petervachon As this was raised as a UAT defect, would you mind providing some guidance around the intended functionality of this?

Should we display the toolbar tooltip on both hover and focus as we do currently, or should we defer it to only being included on hover?

**Comment by petervachon** [comment]
I would defer to displaying the tooltip only on hover.

**Comment by jendowns** [comment]
@SimonFinney @cameroncalder @petervachon Please note that the tooltip must be displayed on `focus` for keyboard-only users.

**Comment by chrismichaelmurphy** [comment]
Did ye come to agreement about this issue ???

**Comment by SimonFinney** [comment]
Closing as per Slack conversation
