### ISSUE TITLE
Is there any codesandbox samples in story book?

### ISSUE THREAD

**Issue by hintcnuie** [carbon-design-system/ibm-security#476]
## Request - 
Is there any codesandbox samples in story book? just as the Carbon Design system does,  it makes a little more clear for developers when have code in codesandbox
### Details
When I try to use the SearchBar,  I get some errors but I can't learn more just from the story book,  since the story book  a little combined storybook grammar and Carbon

- **Application / team -** 
- **Work item -** []()
- **Needed by -** 

### Proposal

![]()

### Goals / use cases

- [ ] 
- [ ] 
- [ ]

**Comment by jendowns** [comment]
Hey @hintcnuie, we have a CodeSandbox linked in the [Getting Started section](https://github.com/carbon-design-system/ibm-security#getting-started) of the project's README: https://codesandbox.io/s/codesandbox-u307t

You can use it to get started on experimenting with components in a more live environment. Would that help?
