### ISSUE TITLE
Panel: Close panel by clicking "off" of panel

### ISSUE THREAD

**Issue by joshkimmell** [carbon-design-system/ibm-security#481]
### Details

- **Application / team -** IBM Security Data Explorer
- **Work item -** n/a
- **Needed by -** n/a

### Proposal

It would make the Panel v2 component a bit more "delightful" and usable if a user could click on the overlay (or anywhere outside of the panel) to close the panel, in addition to clicking the close button.

#### To close the panel, a user can

- [ ] click the overlay
- [ ] use the 'Esc' key

#### Other

- [ ] Functionality is on by default and toggled by a prop

**Comment by JasonKeirstead** [comment]
Also you should be able to trap that click and then re-invoke it on the covered-up area

If we did that, it would help a bit as the user could click from thing to thing - although it is hard to read.

**Comment by SimonFinney** [comment]
@joshkimmell Are these requirements up-to-date? Or has there been additional consideration since?

**Comment by rmccaskill** [comment]
Agree. The need to navigate to the 'X' to close the panel is impediment to flow. The panel that appears on the right side of the shell (which launches apps, settings, etc) closes by clicking "off" of the panel. Would like to see that on the right as well. 

Panel v2 is similar to a modal - the user is forced to interact with the panel.  The carbon modal supports both "click away" and "ESC" to close the modal

Would also suggest supporting closing the panel by pressing 'esc' key.

**Comment by joshkimmell** [comment]
@SimonFinney no other requirements as of now. There is a concept of "pinning" the panel open, but that's outside of the scope of this.

**Comment by MatthewMcP** [comment]
Would you like the closing when clicking elsewhere and closing on esc button to be optional props or have them enabled all the time?

**Comment by rmccaskill** [comment]
Would also like to see the ESC key close the panel.  See comment https://github.com/carbon-design-system/ibm-security/issues/481#issuecomment-624400331

**Comment by SimonFinney** [comment]
@rmccaskill Sorry, I should've kept you updated! See acceptance criteria

**Comment by jamiegodin** [comment]
Congrats guys!
