### ISSUE TITLE
Small tearsheet: responsive layout

### ISSUE THREAD

**Issue by joshkimmell** [carbon-design-system/ibm-security#482]
### Details

- **Application / team -** IBM Security Data Explorer
- **Work item -** n/a
- **Needed by -**n/a

### Proposal

When a user views a tearsheet on an extra-large browser window (see screenshot), the majority of the viewport is taken up by negative space and the tearsheet, which should be the focus of the user's attention, is minimal and hard to interact with. I propose an exploration in responsiveness to address this problem.

![image](https://user-images.githubusercontent.com/8161298/78806875-ed2ec580-7988-11ea-90c8-ade72970262c.png)

### Goals / use cases

- [ ] Responsiveness for large screens
- [ ] Responsiveness for small screens

**Comment by SimonFinney** [comment]
@petervachon Would you have any guidance on how this should behave at larger screen sizes?

**Comment by SimonFinney** [comment]
Scheduling a call next week to discuss

**Comment by SimonFinney** [comment]
## Small

<img width="1680" alt="Small" src="https://user-images.githubusercontent.com/3846874/82073134-b7d86e80-96d0-11ea-9b87-60d2a6cd1c16.png">

## Large

<img width="1680" alt="Large" src="https://user-images.githubusercontent.com/3846874/82073144-bb6bf580-96d0-11ea-8f21-05475f47aa61.png">
