### ISSUE TITLE
Update product title font weights 

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/ibm-security#485]
The font weights should be: IBM (regular) **Security (bold)** Application (regular)

Applies to Shell (Security) & UIShell (Carbon)

Security currently appears to be semibold
![image](https://user-images.githubusercontent.com/50155706/79146829-95c59680-7d88-11ea-840a-014e08130732.png)

**Comment by SimonFinney** [comment]
@cameroncalder You're right! This is semibold, but it's the strongest weight recommended and supplied by Carbon's typography guidance and package - https://carbondesignsystem.com/guidelines/typography/overview#weights

Let me know how you'd like to proceed here.

**Comment by cameroncalder** [comment]
To be brand compliant, we need it to be bold

**Comment by SimonFinney** [comment]
@joshblack Adding you for discussion and additional context - would you mind providing any insight on this?

I see `@carbon/type` only outputs up to semibold - is this correct?

**Comment by joshblack** [comment]
Hey @SimonFinney ! I believe we follow the IDL specification outlined here: https://www.ibm.com/design/language/typography/type-specs-ui#weights 

Let me know if there is an update coming, I may just be missing out on an issue to update the guidance or something, but as it stands today the highest weight specified has been semibold.

**Comment by cameroncalder** [comment]
Hey @joshblack, yeah totally understand your position and it makes sense for the rest of the UI. To be in brand compliance though, universally across all IBM, we need the bold weight to create the proper logotype (All hero brand logotypes use the same structure of regular and bold weights). The alternative to this would be to have all offerings implement as an svg instead of live type..

**Comment by joshblack** [comment]
@cameroncalder could you link to the site you are referring to for these brand requirements? That might help us track down where guidance is diverging.

**Comment by cameroncalder** [comment]
Hey @joshblack, following up here. Are the links above sufficient for what you were after for brand requirements?
