### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by dan-cooke** [carbon-design-system/ibm-security#489]
https://github.com/carbon-design-system/carbon/issues/5873

**Copied from carbon repo** 

I think it would be really cool if we could start writing (or generating) some typings for this project.

Its quite frustrating having to leave my editor everytime i need to check what props are available.
![image](https://user-images.githubusercontent.com/22816887/79454103-92c5e280-7fe2-11ea-85de-0916da6d6c84.png)

`PropTypes` are great for runtime analysis, but most tools cannot statically parse prop types. Editors like VSCode use TS defintion files to provide "intellisense" to users.

Libraries like [material-ui](https://material-ui.com/getting-started/installation/) have fully typed components, have a look at what VSCode is able to provide me for their `Button` component

![image](https://user-images.githubusercontent.com/22816887/79454613-724a5800-7fe3-11ea-851e-d8ec3f2184b5.png)

But just because we are using JS does not mean we need to sacrifice static typing for our consumers - [`.d.ts`](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) files can be used to export type defintions for JS libraries

This is something that I would love to see implemented to improve the developer experience with carbon!

Keep up the great work!

**Comment by SimonFinney** [comment]
Requires further investigation as to whether these could be generated
