### ISSUE TITLE
Request for Resource: Sketch file

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/ibm-security#490]
### Details

- **Application / team -** Desing team
- **Work item -** Sketch file that has all components and patterns of Carbon for IBM Security
- **Needed by -** As soon as possible

We are using carbon for ibm security library but out design team is using the sketch file of carbon. It has many components and patters missing from carbon for ibm security library and having hard time. They are having to recreate the components and the design-development language is missing due to custom implementations by the designers. Please consider making the sketch resource public.

**Comment by SimonFinney** [comment]
@cameroncalder Would you have any insight on the above? Is this something that's currently available?

If so, perhaps @lordsfantasy can reach out to you on Slack for further details

**Comment by lordsfantasy** [comment]
Hello team, any update on this?

**Comment by cameroncalder** [comment]
Hi @lordsfantasy, we certainly see the pain as well. We are planning to release a beta Carbon for IBM Security Sketch library in May.

https://www.ibm.com/brand/systems/security/updates/releasing-soon#product

**Comment by lordsfantasy** [comment]
Hi @cameroncalder, any update on the release of **Carbon for IBM Security Sketch component library**?

**Comment by cameroncalder** [comment]
The Security Sketch libraries are being distributed across a smaller group at the moment and will be widely available later this month. Reach me on Slack if you’d like to participate in early testing

**Comment by lordsfantasy** [comment]
I would love to. Can you please invite me on slack as I am not in your workspace?

**Comment by SimonFinney** [comment]
@lordsfantasy You can reach out to me (`@simon`) on any of the internal IBM Slack workspaces and I'll be happy to connect you

**Comment by lordsfantasy** [comment]
Hey @SimonFinney, I am not from IBM team. I am only a user of Carbon for IBM Security. Are they any plans of making the sketch file available to general public?
