### ISSUE TITLE
TagWallFilter: component does not react completely to the state change

### ISSUE THREAD

**Issue by mohittrivedigit** [carbon-design-system/ibm-security#491]
## Bug - Component does not react completely to the state change. While changing the state after data loads, it does not update the availableItems and selectedItems.

**Expected behavior -**

It should be reactive to the state changes

**Actual behavior -**

It is not reactive to the state changes
### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/confident-dubinsky-6coq4?file=/src/App.js)

1.  Open the codesandbox link
2.  Even though there are 4 available items, but it displays only 1 after state changes

### Affected browsers
- [x] Safari 13.0.4 on Mac OSX 10.15.2

**Comment by mister-what** [comment]
@mohittrivedigit I've a simple solution, that should do the trick for now: 
https://codesandbox.io/s/tag-wall-filter-fix-b7v3g
It basically makes sure, that the component is recreated, when the availableItems props is changed, by assigning a different `key` to the component.

@SimonFinney We should take into consideration, to iterate over this component, to make it consume prop changes into its internal state.
With the current implementation of the tagWallFilter it might be probably not so easy to digest prop changes into the state. So it needs some rewrite in regards on how it maintains its internal state and in regards to its lifecycle when props change.
My proposal would be to go with a hook based approach here:

- currently the TagWallFilter uses recompose to allow a reducer to maintain its state
- I'd suggest to remove recompose and replace it by a `useReducer` hook instead
- additionally there needs to be an effect that takes prop changes into consideration

**Comment by mohittrivedigit** [comment]
@mister-what making the `key` unique for each render is doing the trick. Thank you.
