### ISSUE TITLE
How do I apply cg10 theme at a global level and implement a toggle?

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/ibm-security#496]
Hi, I am unable to decode the theming documentation clearly. Can you please tell me how to apply the cg10 theme at a global level in react?

Is it possible to switch between cg10 and g100 themes using a toggle? How do I implement this functionality? Please guide me through the process.

I can help with extending or simplifying the theme documentation post learning.

I will look forward to your response.

**Comment by SimonFinney** [comment]
Hi @lordsfantasy ! Themes can be toggled by using the CSS classes outlined in the documentation - https://github.com/carbon-design-system/ibm-security/tree/dev/docs/themes#css

Here's a quick CodeSandbox to illustrate the concept - https://codesandbox.io/s/lnd2q

**Comment by lordsfantasy** [comment]
Thanks @SimonFinney , this was helpful! :)
