### ISSUE TITLE
Layout variables mapped to custom properties

### ISSUE THREAD

**Issue by j1mie** [carbon-design-system/ibm-security#509]
SCSS layout variables are mapped to CSS custom properties, so when we perform an operation like: 

```
$spacing-07 / 2;
```

We get an error: 

```
Invalid null operation: "null div 2".
```

### Steps for reproducing

Perform an operation on a sass layout variable.

This appears to have been fixed in v1.21.0-prerelease.2  but reintroduced in (#492) (52efd0c)

**Comment by SimonFinney** [comment]
Thanks @j1mie ! Would you mind creating a reduced test case? I've been unable to reproduce what you're describing in `dev` or [CodeSandbox](https://codesandbox.io/s/codesandbox-gfbmh?file=/src/index.scss).

**Comment by j1mie** [comment]
Thanks @SimonFinney I also tried on a fresh instance of CRA and could not replicate. I'm having the issue with a NextJS project so I will debug and give more detail here.

**Comment by j1mie** [comment]
Updating `@carbon/themes` to `^10.11.2` from `^10.7.0` resolves this issue

**Comment by SimonFinney** [comment]
Blocked by next major release
