### ISSUE TITLE
Toolbar menus (expandable) do not render correctly

### ISSUE THREAD

**Issue by wdiu** [carbon-design-system/ibm-security#515]
## Bug -
1) Try the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Observe that the expandable "> Section 1" is generated properly and can be expanded.

2) Observe that the code that's generated includes a `<div class="security--nav__list__item__link">`.
Get the latest v1.22.0 from today and do the same sample as found at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Observe that the code that's generated does **not** include a `<div class="security--nav__list__item__link">` and the menu doesn't render correctly.

**Expected behavior -**
Should render like the sample at the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default.  Please see screenshot.

**Actual behavior -**
Please see screenshot.

### Steps for reproducing
1) Try the sample at https://ibm-security.carbondesignsystem.com/?path=/story/patterns-toolbar--default without changing anything.

### Screenshots
![ToolbarGeneratingProperly](https://user-images.githubusercontent.com/10282242/80503261-9b51dd80-893f-11ea-849e-18b26f1f27fd.png)
![ToolbarNotGeneratingProperly](https://user-images.githubusercontent.com/10282242/80503264-9bea7400-893f-11ea-9232-ce4303510b5b.png)

### Affected browsers

Chrome Windows 81.0.4044.129 (Official Build) (64-bit)

### Optional information

**Version -** v1.22.0 from today (April 28, 2020)

**Comment by jendowns** [comment]
@wdiu I am unable to replicate this in the storybook environment when on `1.22.0`. 🤔 I'm using the Firefox 75 and Chrome 81 on macOS 10.15.4. 

Are you still seeing this? And do you see it when you observe the `Nav` component as well?

**Comment by wdiu** [comment]
Yes, it still happens with the 1.22.0 build (April 28, 2020 build).

**Comment by wdiu** [comment]
I haven't checked the Nav component yet though.

**Comment by jendowns** [comment]
@wdiu The `Nav` component is used in the `Toolbar`, so I would expect this issue to exist in both components.

However, to reiterate -- I am unable to replicate this. And I also just checked on my Windows 10 machine (build 18362.778) on both Firefox 75 and Chrome 81. Still don't see anything strange with the `Toolbar` as you described.

Could you please provide more information here? Specifically, I'm interested in whether you see the same issue with the `Nav` component's story, whether you have any browser extensions, whether you see any console errors, etc.

Again -- with the information I have, checking multiple environments and browsers, I am unable to see this issue & I'm looking for more information. Thanks!

**Comment by wdiu** [comment]
Hi @jendowns.  Thanks for investigating.  I tried the Nav component (copied the Nav example in the Storybook without changing anything) and got the same result as the part that doesn't render properly in the Toolbar component.

![NavExample](https://user-images.githubusercontent.com/10282242/80756270-3396c080-8b00-11ea-9520-291947eb8cd2.png)

I don't have any browser extensions.

In the Toolbar example, it seemed like the actual generated code was different, so it may not be browser specific.  (The corresponding code is at the bottom of each screenshot.)

As for console warnings:
validateDOMNesting(...): <li> cannot appear as a descendant of <li>.
validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
React does not recognize the `isExpandedOnPageload` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isexpandedonpageload` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Warning: Unknown event handler property `onItemClick`. It will be ignored.
Warning: Unknown event handler property `onListClick`. It will be ignored.

Are you using a React Hot Loading environment?

**Comment by jendowns** [comment]
Thanks for the info @wdiu! When I tested on my Mac, I was running the storybook environment locally, in development.

I'm not sure how those errors would stop the component from rendering correctly. 🤔 

I'm curious if the see the same results in this CodeSandbox demo? It uses `v1.22.0` and I've added the `Nav` component: https://codesandbox.io/s/codesandbox-lu1ru

**Comment by wdiu** [comment]
Hi @jendowns.  Thanks for looking into it.  Yes, the Nav works in your CodeSandbox.  (I also tried Toolbar in CodeSandbox previously and that worked fine.)

I agree the invalid event handler property shouldn't mess up the rendering.  But the validateDOMNesting message could be a result of the wrong rendering.

I wonder if it is related to this issue I ran into when using React Hot Loading: https://github.com/carbon-design-system/carbon/issues/2630

It seems like a fix was made a few days ago here: https://github.com/carbon-design-system/carbon/pull/5929

**Comment by jendowns** [comment]
Thank you @wdiu! When you get a chance, would you mind pulling down my branch `515_navlist-rendering` and seeing if the issue is resolved for you for the `Toolbar` and `Nav`?

**Comment by wdiu** [comment]
![Toolbar3](https://user-images.githubusercontent.com/10282242/80827128-677dee80-8bb1-11ea-9d19-0b8b12ec3ad0.png)

Thanks for the code change, @jendowns.  However, it still looks the same.

**Comment by jendowns** [comment]
Thanks for your patience -- I'll keep looking into this 👍

**Comment by jendowns** [comment]
@wdiu I believe I have a solution now. I set up a separate RHL environment for myself to test... it seemed to work to compare the `type.name` when rendering the `NavList`. When you have a moment, I'd love it if you could take a look at the updated #522 & let me know if the proposed fix works for you. Thanks again for your patience & help with this 👍

**Comment by wdiu** [comment]
Thanks for looking into it, @jendowns.  I didn't get a chance to try it out yet, but that looks like it would fix it.
