### ISSUE TITLE
Bug - Select component requires a size prop

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#534]
**Expected behavior -**
Given that the documentation states that the `size` prop for the `Select` component. The `Select` component should allow consumers to not provide the `size` prop. 

**Actual behavior -**

When a `size` prop is not set to `"sm"` or `"xl"`, a prop-type validation warning is logged:

```
Failed prop type: Invalid prop "size" of value "" supplied to "Select", expected one of ["sm","xl"].
```

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/agitated-sunset-cfvxs?file=/src/App.js)

1.  Render a simple `Select` component
2.  Notice that the console logs a prop-type error for the `size` prop

### Screenshots

![image](https://user-images.githubusercontent.com/5973294/81719802-22747a80-9443-11ea-8f47-11f22b9e49d1.png)

### Optional information

**Version -** 1.22.1

**Comment by SimonFinney** [comment]
Symptom of https://github.com/carbon-design-system/carbon/pull/5481

**Comment by jendowns** [comment]
@SimonFinney @diego-codes I opened a new issue about this here, using Diego's examples: https://github.com/carbon-design-system/carbon/issues/6076

Please feel free to weigh in there 👍

**Comment by jendowns** [comment]
@diego-codes Actually I've closed that issue because I believe this is a versioning problem. The propType warnings were fixed in a recent version of Carbon but we are only on `7.10.0` at the moment. https://github.com/carbon-design-system/carbon/pull/5481 fixed the issue upstream

**Comment by diego-codes** [comment]
Oh, how that's good to know. Thank you~
