### ISSUE TITLE
Bug - Proxied component from Carbon props info is missing data

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#536]
**Expected behavior -**

The props table in the Storybook for every component should include `propType` and description information.

**Actual behavior -**

It looks like components that are proxied over from Carbon do not have their `propType` or `description` information. All of the `propType`s are `node` which is not helpful.

### Screenshots

Example: 
![image](https://user-images.githubusercontent.com/5973294/81743064-ab50dd80-9466-11ea-9b15-0b71d71198c1.png)

### Optional information

**Version -** 1.22.1

**Comment by SimonFinney** [comment]
Thanks for raising! As it stands, this is definitely a known issue with no clear solution besides redirecting to Carbon's Storybook for now
