### ISSUE TITLE
FilterPanel and DatePicker don't work well together

### ISSUE THREAD

**Issue by wdiu** [carbon-design-system/ibm-security#552]
## Bug -

When the DatePicker is used in the FilterPanelSearch area of the FilterPanel, the search portion disappears when trying to select a date.

**Expected behavior -**

The search portion should not disappear.

**Actual behavior -**

The search portion disappears.

### Steps for reproducing

I copied in the examples for the "FilterPanel - default" and the "DatePicker - range with calendar."

Please go to https://codesandbox.io/s/codesandbox-8hqjc?file=/src/index.js
Click the "Find filter - prop" textbox.
Click the calendar.
Click a date.
The entire filters search section disappears.

The same problem happens with the single (not range) version of the calendar when you click the calendar icon (it works in the single version of the calendar when you click on an area other than the calendar icon).

### Screenshots

Please see https://codesandbox.io/s/codesandbox-8hqjc?file=/src/index.js

#### 

### Affected browsers

Chrome Version 81.0.4044.138 (Official Build) (64-bit) Windows

### Optional information

v1.23.0

**Comment by SimonFinney** [comment]
Thanks for raising @wdiu ! @diego-codes I'm curious to hear your initial thoughts on this?

**Comment by diego-codes** [comment]
Yeah that's a tough thing to manage. The cause of this that the keyboard focus shifts into calendar UI causing the search results section to disappear because it no longer contains the focus.

On the other hand, I think that the filter panel search results section is not a good place for the `DatePicker`. It introduces too many floating contexts that is confusing to navigate. What is the use case for the date picker inside of the results?

**Comment by wdiu** [comment]
Hi @diego-codes, thanks for looking into it.  The reason we have it in the filters is to narrow down the results by a start and end date.  It was in the main filters area, so we figured it should also be available in the drop-down filters area (i.e. search results section).

**Comment by Yohanna** [comment]
Not stale.

**Comment by SimonFinney** [comment]
Thanks @Yohanna - Are there designs to support what the issue is describing? Could you share them with me via Slack?
