### ISSUE TITLE
Divider between buttons in IconButtonBar

### ISSUE THREAD

**Issue by lythedev** [carbon-design-system/ibm-security#568]
### Details

- **Application / team -** Advisor

### Proposal

The first two buttons in our IconButtonBar is used to switch between views. The third button can be used on either view, so we've added a "divider" before the third button. This divider is actually just a left border on the third button. It would be nice to have an actual divider element between the buttons because on focus the buttons' border covers the "divider".

![image](https://user-images.githubusercontent.com/7308832/82932979-42359380-9f57-11ea-856f-eb5bc26c0629.png)

### Goals / use cases

- [ ] Be able to add a divider between buttons

**Comment by SimonFinney** [comment]
## Acceptance criteria

- [ ] Pass spread attributes for the `IconButtonBar`, actions, and overflow menu

**Comment by SimonFinney** [comment]
@petervachon Would you have any guidance around this?

**Comment by petervachon** [comment]
I believe @cameroncalder just had a suggestion for this. Cameron, I think you showed an option for this to Jimmy. Can you provide guidance?

**Comment by cameroncalder** [comment]
Yeah, here's another example. Similar to the above example where the divider is used to separate toggles & actions.

![image](https://user-images.githubusercontent.com/50155706/83140958-7ecad180-a0b4-11ea-86ef-65ddd2c0b268.png)

**Comment by jendowns** [comment]
Hey everyone, I think this can be achieved with `box-shadow` instead of `border`, without refactoring the component. I'll propose a PR with a storybook example shortly.

**Comment by cameroncalder** [comment]
Divider colors would be Cool Gray 20 / Gray 80
