### ISSUE TITLE
Modal component frozen in Chrome when the Modal content is long

### ISSUE THREAD

**Issue by hangdu1102** [carbon-design-system/ibm-security#577]
## Bug - In Chrome browser, the Modal is frozen and not usable anymore when the Modal content is longer than around screen size. 

Issue seen in In this Modal component https://ibm-security.carbondesignsystem.com/?path=/story/components-modal--default

**Expected behavior -** Modal should behave as expected regardless of the size of content in the Modal, so the styling should keep the same and Modal should be closable.

 

**Actual behavior -** When put long content inside Modal, click something inside Modal, the Modal will not be responding anymore. Styling looks broken and Modal not closable.

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.   Use Google Chrome and put a Modal with React on the page.
2.   Set long content (example: a list of more than 100 checkbox items) inside Modal.
3.   Click the bottom area or the last checkbox item inside the Modal, then the Modal will be frozen.

#### 
![]()

<img width="924" alt="image" src="https://user-images.githubusercontent.com/24817328/83250280-c8dcb180-a19f-11ea-8d3a-fe2a8995ca5b.png">

#### 
![]()

<img width="924" alt="image" src="https://user-images.githubusercontent.com/24817328/83250464-10633d80-a1a0-11ea-9fc0-6a52891ec6e8.png">

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

On Mac OSX 10 
Chrome Version 81.0.4044.138 (Official Build) (64-bit) (not sure about other version, may affected)
Seen on Development Environment (it is working fine with Firefox browser)

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
Hi @hangdu1102 ! Could you confirm if this issue still exists or if you managed to resolve it?

**Comment by hangdu1102** [comment]
Hi @SimonFinney 
I replaced the useage of Modal with TearsheetSmall component, so I am no longer face the Modal issue.
( https://github.com/carbon-design-system/ibm-security/issues/647 )
Thanks for the support : )
