### ISSUE TITLE
Panel content border update

### ISSUE THREAD

**Issue by joshkimmell** [carbon-design-system/ibm-security#582]
### Details

- **Application / team -** IBM Data Explorer
- **Work item -** []()
- **Needed by -** 

### Proposal

There are 2 types of content identified for the side panel: `Panel content section` and `Fragment`. I propose we handle them differently in terms of styling. This will fix a lot of the visual discrepancies we're currently experiencing. 

![Artboard](https://user-images.githubusercontent.com/8161298/83550771-fb065000-a4cc-11ea-9d2e-d6c6aa56e80d.png)

### Goals / use cases

- [ ] 
- [ ] 
- [ ]

**Comment by jendowns** [comment]
Hey @joshkimmell I was looking into the requirements here and am curious about the requirement:

> if first child, no top padding

In a previous PR, padding was adjusted to only be provided as part of the child `PanelContent` component, so with that requirement as-is the first `PanelContent` child of a `PanelV2` will look like this (with content right against the header area):

<img width="341" alt="Screen Shot 2020-06-29 at 4 05 19 PM" src="https://user-images.githubusercontent.com/9057921/86056173-a1893680-ba22-11ea-99b6-8f1431d1607d.png">

Is this the intention or can you elaborate on what should be changed? Thank you!

**Comment by jendowns** [comment]
Hey @joshkimmell just checking in -- do you have any feedback on https://github.com/carbon-design-system/ibm-security/issues/582#issuecomment-651367382? Thanks!

**Comment by joshkimmell** [comment]
A few things... 

1. so since the header is fixed and things scroll behind it, the bottom border should span the width of the panel, providing a logical barrier.  
![image](https://user-images.githubusercontent.com/8161298/88565395-26537a00-cffa-11ea-98d1-631acd13902d.png)

2. The body is currently set with a margin-top of 107px, but with the new header height, should be reduced to 92px.
![image](https://user-images.githubusercontent.com/8161298/88565738-a37eef00-cffa-11ea-8eab-8b90039d4a98.png)

**Comment by joshkimmell** [comment]
because fragments should span the entire width of the panel (like the header), they need to either be separated from the content container OR the content container should not specify the padding at all.
