### ISSUE TITLE
DataDecorator for long text behaviour changed

### ISSUE THREAD

**Issue by lidiya101** [carbon-design-system/ibm-security#591]
Expected behavior -

When there is a long text inside a data decorator, on V1 it used to replace it with elipsis. 

Actual behavior -

Long text is shown as is no matter how long
![image](https://user-images.githubusercontent.com/6652483/83867129-3ac97380-a729-11ea-9e7b-183e621868cb.png)

Steps for reproducing
Check out the storybook & add very long text:
https://ibm-security.carbondesignsystem.com/?path=/story/components-decorator--default

**Comment by SimonFinney** [comment]
@jimmydyer / @petervachon What should the expected behavior here be?

**Comment by jamiegodin** [comment]
@SimonFinney, if you want to go over this let me know :)
https://github.ibm.com/QRadar/qradar-shiftypixels/issues/88

**Comment by jimmydyer** [comment]
Hmm... well, we shouldn't allow this component to go on with an infinite amount of text. It should at least adhere to the design principles around body copy length (which I think is 6 columns max). @petervachon can correct me on this. But I'm wondering if we just need to create a rule for character amount?

Also, if this component is used within a container (i.e. table column, card, etc.), then it should add an [...] at the end of the component and not wrap.

**Comment by joshkimmell** [comment]
To be clear, the above issue (https://github.ibm.com/QRadar/qradar-shiftypixels/issues/88) relates to truncation in filter tags, not decorators. I do think we can use this as a guide, though. There are going to be different rules for decorators in tables vs. inline decorators / decorators outside of a table.

**Comment by joshkimmell** [comment]
Also, @jimmydyer is right. Decorators should always be single line.
