### ISSUE TITLE
Bug: recompose dependency causes React warnings

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#602]
**Expected behavior -**
When rendering components from `@carbon/ibm-security` the web console should be as clean as possible when there are not prop-type errors. This way, we can reduce console noise and focus on real issues. 

**Actual behavior -**

When rendering components from `@carbon/ibm-security`, we get numerous warnings that look like this:

```
console.warn node_modules/react/cjs/react.development.js:315
    Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
```

When digging further, here is what I see:
![image](https://user-images.githubusercontent.com/5973294/84198032-8f8e2680-aa68-11ea-969c-f70a4536f4e3.png)

Notice that the stack trace highlights `recompose` used by the `TagWallFilter` component. I dug deeper and found [this comment](https://github.com/enzymejs/enzyme/issues/2344#issuecomment-592965549). It appears that `recompose` is causing the problem. 

Additionally, the `recompose` project has been [sunset close to two years ago](https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018). 

### Steps for reproducing

1.  Render any component with the following style of import:
    ```
    import { Button } from '@carbon/ibm-security';
    ```
2. Check the console and notice the warning.

### Optional information

**Version -** 1.25.0

**Comment by Nikita-Samoilenko** [comment]
yes, it is still relevant
`    console.warn
      Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.

      138 | };
      139 | 
    > 140 | export default compose(
          |                ^`

**Comment by obambrough** [comment]
Recompose has a transitive dependency on node-fetch ^1.0.1, which is flagged as a security vulnerability by yarn audit.

**Comment by SimonFinney** [comment]
> Recompose has a transitive dependency on node-fetch ^1.0.1, which is flagged as a security vulnerability by yarn audit.

Potential solution - https://github.com/acdlite/recompose/issues/817#issuecomment-725033148
