### ISSUE TITLE
Component theme issues against container backgrounds

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/ibm-security#609]
Reference example:
https://layout--ibm-security.netlify.app/?path=/story/patterns-unstable-layout--overview
![image](https://user-images.githubusercontent.com/50155706/84412002-36db9c80-abd4-11ea-909f-4917516b6754.png)
![image](https://user-images.githubusercontent.com/50155706/84412043-4529b880-abd4-11ea-8fd0-80aead4416db.png)

Gray 100/Cool Gray 10 themed components placed on top of containers where the background colors are Gray 90/White have conflicting base colors. Example shows the Content Switcher but it applies to any component that has a base color of either Gray 90 or White.

**Comment by SimonFinney** [comment]
As discussed, this likely requires proposing a `light` variant of the `ContentSwitcher` to Carbon

**Comment by SimonFinney** [comment]
See https://github.com/carbon-design-system/carbon/issues/6309
