### ISSUE TITLE
[Wizard] - The step titles are truncated when they exceed a single line. 

### ISSUE THREAD

**Issue by Deriohig** [carbon-design-system/ibm-security#617]
## Bug - wizard truncated text when it exceeds a certain number of characters (roughly 25~)
**Expected behavior -**

The user can access the whole string passed into the step's title

**Actual behavior -**

the title is truncated and not viewable in the left hand panel when over around 25 characters

### Steps for reproducing

1.  define a wizard step title with over 25~ or so characters

### Screenshots

![image](https://user-images.githubusercontent.com/7848154/84797514-d2647700-aff1-11ea-84f3-475408d4d9c1.png)

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [x ] Chrome for  Mac OSX 

### Optional information

**Version -** 1.21

**Comment by jendowns** [comment]
So it looks like part of the solution for this, if we go with the `title` route, will involve this PR: https://github.com/carbon-design-system/carbon/pull/6293
