### ISSUE TITLE
Filter panel - page scroll down after check item

### ISSUE THREAD

**Issue by galamo** [carbon-design-system/ibm-security#621]
attached video - explained the issue.
when selecting the relevant item, the screen scroll down ( issue solved with saving the last scroll y value before selecting and setting it to the window.scrollY after clicking - but is surly workaround )

video uploaded to : https://ibm.ent.box.com/folder/115797939983 @SimonFinney have access

**Comment by SimonFinney** [comment]
Thanks @galamo ! @diego-codes I'm curious if this is an issue that you have faced in the past with the `FilterPanel` that you may be able to provide some guidance on? I've shared the video with you on Box

**Comment by diego-codes** [comment]
Hi there. We don't have this issue in DE. As far as I can tell, there is nothing to the filter panel implementation that would cause this issue. Perhaps it is related to the filtering implementation?

**Comment by galamo** [comment]
@diego-codes , but this issue caused when we are checking an checkboxitem from the panel.
what is your suggestion?

**Comment by diego-codes** [comment]
Without knowing more specifics, I'm not sure. To zero in on the possible issue, I suggest that you test applying a filter using a different method (like a Button) and see if the page has the same scroll issues once a filter is applied. This would help you determine if the issue is the filter panel or something else.

**Comment by SimonFinney** [comment]
@galamo - Could it be that you have the same IDs for the filter panel items and the cards? It's just a thought, but it might explain the scrolling

**Comment by galamo** [comment]
@SimonFinney 
No, the ids are different, for sure
