### ISSUE TITLE
DataTable - Option to configure sticky table header 

### ISSUE THREAD

**Issue by galamo** [carbon-design-system/ibm-security#622]
currently there is no support in the Header Datatable to be sticky to the top of the table when scrolling

 Trusteer - IBM

**Comment by SimonFinney** [comment]
Thanks @galamo ! This should now be available in [`v1.26.0`](https://github.com/carbon-design-system/ibm-security/releases/tag/v1.26.0) - You can verify by using the knobs in https://ibm-security.carbondesignsystem.com/?path=/story/components-datatable--default
