### ISSUE TITLE
Hover state on shell toolbar buttons

### ISSUE THREAD

**Issue by rebecca-m-l** [carbon-design-system/ibm-security#637]
## Bug - In the Storybook, the hover and selected states of the toolbar buttons don't fill the full width of the bar so they have a border around them.

**Expected behavior**

The hover 'square' fills the full width of the toolbar so that it bleeds to the edges

<img width="200" alt="Screenshot 2020-06-24 at 16 18 47" src="https://user-images.githubusercontent.com/56588740/85584542-247f4b00-b637-11ea-825c-42cfd0b93224.png">

**Actual behavior**

It doesn't bleed to the edge so there's a border

<img width="272" alt="Screenshot 2020-06-24 at 16 19 18" src="https://user-images.githubusercontent.com/56588740/85584600-3234d080-b637-11ea-88f1-d3299e87b535.png">

**Comment by SimonFinney** [comment]
Requires breaking change

**Comment by Rebecca-love** [comment]
@SimonFinney 
<img width="600" alt="Screenshot 2020-06-25 at 14 58 24" src="https://user-images.githubusercontent.com/56588740/85733763-5c989380-b6f4-11ea-95f3-9b029f439d84.png">
