### ISSUE TITLE
CodeSandbox examples are not working

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/ibm-security#641]
The CodeSanbox samples demoing IBM-Security are not compiling correctly.

### Steps for reproducing

- https://codesandbox.io/s/nmmqp

- https://codesandbox.io/s/codesandbox-u307t

### Screenshots

![image](https://user-images.githubusercontent.com/6926228/85865393-cfa51700-b793-11ea-8516-131abffe2a36.png)

### Affected browsers

Chrome 83 - Windows 10

### Optional information

Carbon Version: `v1.25.0`

**Comment by SimonFinney** [comment]
Potentially related to #599

**Comment by SimonFinney** [comment]
I've isolated this to the `Tag` import - https://codesandbox.io/s/codesandbox-rh6st?file=/src/index.js

**Comment by SimonFinney** [comment]
Verified as resolved in https://codesandbox.io/s/httpsgithubcomcarbon-design-systemibm-securityissues641-rh6st?file=/src/index.js - we can close this out once the official release is created.
