### ISSUE TITLE
security--scroll-gradient color issue on TearsheetSmall (with body)

### ISSUE THREAD

**Issue by hangdu1102** [carbon-design-system/ibm-security#647]
## Bug - security--scroll-gradient color on TearsheetSmall doesn't match Light Theme Mode

**Expected behavior -**  Expect work same as it is in storybook when importing in other code base

**Actual behavior -**  class="security--scroll-gradient__before" and class="security--scroll-gradient__after" showing wrong color under light theme mode

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1. On latest master branch of resilient-core under light theme mode 
2. Importing a TearsheetSmall (with body) component with some long text contnet inside body
3. Scroll up and down, the security--scroll-gradient color issue will be seen

#### 

![image](https://user-images.githubusercontent.com/24817328/86265959-6c185080-bbbc-11ea-88b3-5ed6d8eae918.png)

#### 
![image](https://user-images.githubusercontent.com/24817328/86266002-7d615d00-bbbc-11ea-82f1-18160ca85726.png)

![]()

#### 

![image](https://user-images.githubusercontent.com/24817328/86266095-9cf88580-bbbc-11ea-84c4-4fff0efcf1d6.png)

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

On Mac OSX 10
Chrome Version 81.0.4044.138 (Official Build) (64-bit).  Development

On Mac OSX 10
Firefox 77.0.1 (64-bit) Development

**Comment by SimonFinney** [comment]
Marking this as a spike as well, as it requires further investigation for this to play nice with the offering's unique circumstances
