### ISSUE TITLE
Add support for 'size' prop in DataTable

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/ibm-security#664]
Add support for `size` prop in `DataTable`. The base Carbon library already supports this [option here](https://github.com/carbon-design-system/carbon/blob/fe23a6f46b001e56d31376cfebe6e523b27e77f9/packages/react/src/components/DataTable/DataTable.js#L111)

**Comment by jendowns** [comment]
Hey @Yohanna, have you had issues using the `size` prop? While it isn't shown/used in the storybook demos, there's a spread attribute that will allow you to pass it in:
https://github.com/carbon-design-system/ibm-security/blob/6172791f986cbb5d6214ede59e49b7fe7b4c6f80/src/components/DataTable/DataTable.js#L49

**Comment by Yohanna** [comment]
I tried adding a `size="compact"` on the `DataTable` component but it didn't have any effect.

Adding `className="bx--data-table--compact` on the `Table` component works though.

**Comment by Yohanna** [comment]
Here's a repro of the problem: https://codesandbox.io/s/codesandbox-jrd6p?file=/src/index.js

It seems it doesn't work with the `render` prop pattern. If you comment out the `render` prop it works fine.

**Comment by SimonFinney** [comment]
Hi @Yohanna - thanks for raising! You'll need to use the `getTableProps` parameter that's outputted from the `render` method - https://codesandbox.io/s/codesandbox-kubvz

**Comment by Yohanna** [comment]
Hey @SimonFinney & @jendowns, `getTableProps` did the trick! Thanks!

Btw it looks like this wasn't working in v`1.25.0`, I had to upgrade to v`1.27.0` to get it to work.

**Comment by jendowns** [comment]
Good to hear @Yohanna!

Also the versioning situation you mention makes sense. If you view the git history of the line I linked to above, it was added a month ago...
https://github.com/carbon-design-system/ibm-security/blame/6172791f986cbb5d6214ede59e49b7fe7b4c6f80/src/components/DataTable/DataTable.js#L49

...as part of a PR that was merged and released in `1.26.0`: https://github.com/carbon-design-system/ibm-security/pull/604#issuecomment-644634107
