### ISSUE TITLE
DataTable - Add option to resize & order (drag&drop)  & selectable columns

### ISSUE THREAD

**Issue by galamo** [carbon-design-system/ibm-security#665]
Currently the Datatable is not supported with:
resizable columns
re-ordering columns
selectable columns

is there an option to implement this features in datatable?

**Comment by galamo** [comment]
@SimonFinney  any update here regarding the ticket?

**Comment by rmccaskill** [comment]
Example of resizing
https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-resize-and-initial-column-widths-and-hidden-column
