### ISSUE TITLE
docs(codesandbox): link in README is not working

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/ibm-security#669]
The Codesandbox link on the README file is pointing to a 404 page: https://codesandbox.io/s/codesandbox-nmmqp

![image](https://user-images.githubusercontent.com/6926228/87686221-3fcf0900-c752-11ea-9048-fa635ea024e2.png)

**Comment by SimonFinney** [comment]
We likely need to follow Carbon's lead here and sync our own examples to prevent these from getting moved around or removed accidentally - https://github.com/carbon-design-system/carbon/blob/master/packages/react/examples/codesandbox

**Comment by SimonFinney** [comment]
Thanks @Yohanna , this will now be available at https://codesandbox.io/s/github/carbon-design-system/ibm-security/tree/dev/examples/codesandbox - the links in the README have also been updated
