### ISSUE TITLE
[Card] title is capitalised when using header render prop

### ISSUE THREAD

**Issue by Deriohig** [carbon-design-system/ibm-security#677]
## Bug - CSS capitalisation in Card component 

**Expected behavior -**

No css capitalisation when using the header render prop

**Actual behavior -**

CSS capitalisation when using the header render prop.

### Steps for reproducing

Check the storybook and see the style applied on the title. 

https://experimental--ibm-security.netlify.app/?path=/story/components-card--content

### Screenshots

![image](https://user-images.githubusercontent.com/7848154/87958186-1fcc7c00-caa9-11ea-80e3-0a2ba35388c3.png)

**Comment by SimonFinney** [comment]
@jendowns Do you think we should consider a fix for this a breaking change?

**Comment by jendowns** [comment]
Hey @SimonFinney I wouldn't consider this a breaking change, just an ordinary layout update. Were you thinking this update would be disruptive?

**Comment by SimonFinney** [comment]
I had originally thought for any existing consumers relying on it to transform text that it would surface issues, but that's something that would require fixing on their end sooner or later anyway
