### ISSUE TITLE
Decorator onClick is not working in version 1.28.0

### ISSUE THREAD

**Issue by joemc11** [carbon-design-system/ibm-security#692]
This works in version 1.27.0 and is introduced in version 1.28.0
1. Create a Decorator component
2. Add an onClick event
3. Click on Decorator

**Expected behavior -**
onClick event to be invoked

**Actual behavior -**
onClick is not called

### Steps for reproducing
<Decorator noIcon value="test1" onClick={() => console.log('click')} />

**Comment by SimonFinney** [comment]
Hi @joemc11 ! I've been unable to verify in https://codesandbox.io/s/thirsty-jepsen-o2yvo - Can you create a reduced test case for reproduction?

**Comment by joemc11** [comment]
Hey Simon you are correct Decorator on it own is fine, onClick is invoked.  I was able to fix this in our repo under this pull request, https://github.ibm.com/QRadar/qradar-ui/pull/3024/files.  Bizarely removing onBlur={() => setIsTooltipOpen(false)} in file packages/qradar-user-interface/src/components/HoverableTooltip/HoverableTooltip.js fixes it for us.  Strangely this worked fine in ibm-security 1.27.0.

**Comment by SimonFinney** [comment]
Interesting! I believe the only change since the last version was https://github.com/carbon-design-system/ibm-security/pull/654/files , but it seems non-disruptive 🤔

**Comment by joemc11** [comment]
That may be the cause our component HoverableTooltip.js uses Tooltip internally.  At least we are all good for upgrade.
