### ISSUE TITLE
No padding for tab content when content is table 

### ISSUE THREAD

**Issue by lidiya101** [carbon-design-system/ibm-security#699]
## Bug 

**Short Description -**

After talking with design(@jimmydyer), if the tab content is a  table and  the table has no actions above it, there should not be any padding/margin at bottom, at least he recommends it. This was the behaviour in carbon v1, but it not the case for v2. 

Carbon v2(now):
![image](https://user-images.githubusercontent.com/6652483/88544171-48102980-d019-11ea-942f-65a306e9831c.png)

Carbon v1(before): 
![image](https://user-images.githubusercontent.com/6652483/88547161-a0492a80-d01d-11ea-940d-ae49482b5a1c.png)

**Expected behavior -**

No padding-bottom(margin) for tab content when it is table. 

**Actual behavior -**

padding-bottom(margin) inserted for tab content. 

```
.bx--tab-content {
    padding: 1rem;
}
```

**Comment by SimonFinney** [comment]
I don't think there's a logical way for us to solve this via CSS, besides adding an additional prop that removes the padding from the container entirely. I believe Carbon already supports a prop for `tabContentClassName` that could wield the same result in this case - https://react.carbondesignsystem.com/?path=/story/tabs--default

**Comment by lidiya101** [comment]
Alright Thanks
