### ISSUE TITLE
Tooltip implementation effected by overflow

### ISSUE THREAD

**Issue by Yanipo5** [carbon-design-system/ibm-security#701]
Expected behavior like material design, tooltip shows.
where as in Carbon, I can't see the Toolip.

Material
![image](https://user-images.githubusercontent.com/29729128/88777453-e920f080-d18f-11ea-9e98-be0f0ea83e4c.png)

Carbon
![image](https://user-images.githubusercontent.com/29729128/88777649-1ec5d980-d190-11ea-8563-542a79dfa72b.png)

I guess this issue arise from the table.
```tsx
import { TooltipIcon } from "@carbon/ibm-security";
import { Tooltip as Material_Tooltop } from "@material-ui/core";
...
  return (
    <span>
      <Material_Tooltop placement="top" title={"Material Tooltip"}>
        <span>ma </span>
      </Material_Tooltop>

      <TooltipIcon tooltipText="Carbon TooltipIcon">
        <span style={{ color: "white" }}>ca</span>
      </TooltipIcon>
    </span>
  );
```

Solved by applying overflow:visable (which is not necessary for material)
![image](https://user-images.githubusercontent.com/29729128/88778237-ef639c80-d190-11ea-912a-957c6b61e209.png)

    "@carbon/ibm-security": "1.28.0",

**Comment by SimonFinney** [comment]
Hi @Yanipo5 ! Could you connect with me on Slack with a link to the source code leveraging the `DataTable`?

**Comment by SimonFinney** [comment]
Reduced test case - https://codesandbox.io/s/gifted-spence-j8kzl

**Comment by Yanipo5** [comment]
Hi,
Sure when are you available?
ping me on slack Yaniv Peretz

**Comment by Yanipo5** [comment]
@SimonFinney could we setup a call sometime?

**Comment by SimonFinney** [comment]
Absolutely! Feel free to reach out on Slack (@simon) to discuss, or find 30 minutes on my calendar - thank you!

**Comment by Yanipo5** [comment]
Cool I'll arrange a meeting
