### ISSUE TITLE
Make Tag wall filter Search bar  fixed on top  

### ISSUE THREAD

**Issue by lidiya101** [carbon-design-system/ibm-security#702]
## Request 
Fix Search bar on top

- **Short description -**

The search bar currently disappear when user scrolls down the list of options. It would help the users if the search bar was always visible for easy access. 
 

### Details
https://ibm-security.carbondesignsystem.com/?path=/story/patterns-tagwallfilter--tagwall-with-filter-list-for-multiselect
- **Application / team -** TII
- **Work item -**  -[]()
- **Needed by -** TII 

### Proposal
Make Tag wall filter search bar stay on top

**Comment by SimonFinney** [comment]
@petervachon I'm looking for guidance on the above request - does this make sense or are there any other considerations that need to be made?

**Comment by petervachon** [comment]
@SimonFinney This recommendation makes sense to me 👍 . One item that we will need to consider in future revisions is truncating the visible list of 'selected' tags to 2 or 3 lines with a "10 more" or something like that to save real estate but doesn't necessarily need to be part of this update.
