### ISSUE TITLE
Mouse Events not captured by Notification on click when PanelV2 is open. 

### ISSUE THREAD

**Issue by IshratPahalwi** [carbon-design-system/ibm-security#703]
## Bug - 

Expected behavior:
When both Panel and Notification are opened, both should be responding to mouse/keyboard interactions. 

Actual Behaviour:
When both Panel and Notification are opened, it seems that Panel capture all the mouse events and Notification does not respond to any mouse events.

Version:1.26.0

**Comment by SimonFinney** [comment]
Possibly related to #700

**Comment by SimonFinney** [comment]
Starting reduced test case here - https://codesandbox.io/s/dazzling-chatelet-eet6q
