### ISSUE TITLE
NavItem - Error when using next.js Link component from next/link as element type

### ISSUE THREAD

**Issue by andyjbell1** [carbon-design-system/ibm-security#706]
## Bug - NavItem error when using next.js Link component from next/link as element type

When trying to use the `NavItem` component with the Next.js router by passing in the Link component from `next/link` an error is returned upon render. I have tried using the Link component from `react-router` and this works as expected in `NavItem`. 

I have also tried using the Link from `next/link` as the element prop with Carbons `HeaderMenuItem` and this works. See CodeSandbox below for examples. 

**Expected behavior -**
NavItem component to render a Link `next/link` component. 

**Actual behavior -**
Error is returned when trying to render component. 
`React.Children.only expected to receive a single React element child.`

I have tried different variations of the component child, removing spaces, with/without anchor tags etc, each causing the same error.

### Steps for reproducing

[CodeSandbox] 
Example using Create Next App - https://codesandbox.io/s/github/andyjbell1/NextNavItemTest

Create a NavItem Component with Link from `next/link` as the `element` prop. 

#### Code with NavItem Component highlighted. 
![Screenshot 2020-07-31 at 15 43 11](https://user-images.githubusercontent.com/69004173/89046322-b3713880-d344-11ea-9b58-a918e6cc94d8.png)

#### Screenshot of error.
![Screenshot 2020-07-31 at 15 42 20](https://user-images.githubusercontent.com/69004173/89046371-c5eb7200-d344-11ea-9fe0-db411276bfd6.png)

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -** 
1.28.0

**Comment by leodrez** [comment]
Same issue. Any workarounds so far?
