### ISSUE TITLE
Invalid use of footer in Shell notifications panel

### ISSUE THREAD

**Issue by benborgers** [carbon-design-system/ibm-security#717]
## Bug - I think the use of <footer> in the Shell component's notifications panel isn't semantically valid. 

The bottom of the notification panel in the `Header` component (which is used as part of the `Shell` component) is a `<footer>`. 

<img width="1792" alt="Screen Shot 2020-08-06 at 10 46 49 AM" src="https://user-images.githubusercontent.com/30215449/89546824-029aeb80-d7d3-11ea-9427-532732354d61.png">

The Insights accessibility testers raised the issue that a `<footer>` shouldn't be used without an accompanying element that is `role="main"` (basically, I think the footer needs _something_ to be a footer for). 

I did some research and it looks like each page [should only have one main element](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element). It doesn't seem like making the notification panel the page's one main element would make sense, so therefore `<footer>` probably isn't the right element for the notification panel. 

---

Here are the lines in the `Header` component: 

https://github.com/carbon-design-system/ibm-security/blob/4606908cbb67e326fcd416e4fe1907f07f6d388c/src/components/Header/Header.js#L376-L390

### Optional information

**Version -** `1.28.0`

**Comment by jendowns** [comment]
Can confirm this an issue 👍 The fix should be straightforward so I'm happy to take this one.

**Comment by benborgers** [comment]
I totally agree! I think you're right, multiple `footer` elements would make sense depending on the situation. But just the "View more" link at the bottom of that panel doesn't seem to fit the W3C description of a standard footer.
