### ISSUE TITLE
Bug - ComboButton does not account for the window scroll position

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#724]
**Expected behavior -** 

The `ComboButton` overflow items are positioned appropriately relative to the overflow button regardless of the window scroll position.

**Actual behavior -** 

The `ComboButton`overflow items are not positioned correctly when the user has scrolled on the page.

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/youthful-http-3rd9w)

1. While at the top of the window, click on the overflow menu
2. Notice the position of the overflow menu relative to the button (it looks correct)
3. Scroll down the page by a noticeable amount
4. Click on the overflow menu to view the overflow options again
5. Notice the position of the overflow menu relative to the button (it does not look correct)

#### Before scroll

![image](https://user-images.githubusercontent.com/5973294/89826666-3439ec80-db1c-11ea-8103-a1900203f29e.png)

####  After scroll

![image](https://user-images.githubusercontent.com/5973294/89826629-27b59400-db1c-11ea-9d1a-3363027d5957.png)

### Optional information

**Version -** 1.29.0

**Comment by SimonFinney** [comment]
Carbon reduced test case - https://codesandbox.io/s/festive-currying-2g1zj

**Comment by diego-codes** [comment]
Yes! Good point!
