### ISSUE TITLE
SASS issue - New Project setup

### ISSUE THREAD

**Issue by fahadfax** [carbon-design-system/ibm-security#728]
## Bug - 
I am not sure whether this is a bug or config issue. I created a React app using CRA and added  ibm-secirity using _yarn add @carbon/ibm-security_.  I am following the steps described in [(https://github.com/carbon-design-system/ibm-security)] for creating the App. When I am trying to import @import '@carbon/ibm-security/scss/index', I am getting the below error. 

`_./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
SassError: File to import not found or unreadable: @carbon/themes/scss/mixins.
        on line 7 of node_modules/@carbon/ibm-security/scss/globals/theme/_index.scss
        from line 7 of node_modules/@carbon/ibm-security/scss/globals/_index.scss
        from line 7 of node_modules/@carbon/ibm-security/scss/index.scss
        from line 5 of C:\Trials\React\ibm-secuirity-trial\src\index.scss
>> @import '@carbon/themes/scss/mixins';_`

**Expected behavior -**

**Actual behavior -**

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  
Create a new React App using create-react-app
2.  
yarn add @carbon/ibm-security
3.  
Rename index.css to index.scss and import ibm-security styles by
`@import '@carbon/ibm-security/scss/index';`

run the app by `yarn start`
#### 

![]()
![image](https://user-images.githubusercontent.com/15314288/90311070-30351280-df00-11ea-89a4-bb84313004a5.png)

#### 
package.json
![image](https://user-images.githubusercontent.com/15314288/90311089-4e9b0e00-df00-11ea-8ac2-dc684b853338.png)

![]()

#### 
sass_path configuration (windows OS)

![image](https://user-images.githubusercontent.com/15314288/90311103-6a9eaf80-df00-11ea-917a-a3528965abb4.png)

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
Hi @fahadfax - Thanks for raising! Please reach out on Slack (`@simon`) to debug and discuss further

**Comment by fahadfax** [comment]
Hi @SimonFinney - sorry, I am not familiar with Slack. :( Is there any other way I can message you? 

I have created a github repo with my React app code. [https://github.com/fahadfax/ibm-secuirity-trial.git](https://github.com/fahadfax/ibm-secuirity-trial) 

Please note that I followed [https://www.carbondesignsystem.com/tutorial/react/step-1](https://www.carbondesignsystem.com/tutorial/react/step-1) and [https://github.com/carbon-design-system/ibm-security/](https://github.com/carbon-design-system/ibm-security/) to setup the react app.

Steps to reproduce the error.:-
1) `yarn create react-app ibm-security-trial`
2) `yarn add @carbon/ibm-security`
3) `yarn add node-sass`
4) rename index.css & app.css to index.scss & app.scss respectively (i just followed the carbon tutorial for react) and updated this file name change in index.js and and app.js.
5) create .env file to define SASS_PATH=./node_modules (Windows OS)
6) add `@import '@carbon/ibm-security/scss/index';` in index.scss file.
7) `yarn start`

`yarn start` gives the below error message

```
./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)
SassError: File to import not found or unreadable: @carbon/themes/scss/mixins.
        on line 7 of node_modules/@carbon/ibm-security/scss/globals/theme/_index.scss
        from line 7 of node_modules/@carbon/ibm-security/scss/globals/_index.scss
        from line 7 of node_modules/@carbon/ibm-security/scss/index.scss
        from line 5 of C:\Trials\React\ibm-secuirity-trial\src\index.scss
>> @import '@carbon/themes/scss/mixins';
```

**Comment by fahadfax** [comment]
Hi... this is not relevant. you may please close it.
