### ISSUE TITLE
Bug - Overflow menu mis-alignment on filterpanelcheckboxwithoverflowmenu component

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#747]
### Steps:

1. On https://ibm-security.carbondesignsystem.com/?path=/story/patterns-filterpanel-filterpanelcheckboxwithoverflowmenu--default, open and close the overflow menu
several times 
2. Observe the position of the overflow menu relative to the filter panel

### Expected behaviour
Overflow menu is directly under the filter panel

<img width="212" alt="image" src="https://user-images.githubusercontent.com/56437682/92364510-18117700-f0eb-11ea-9b7b-bd12d68bdc76.png">

### Actual behaviour
Overflow menu gets mis-aligned

<img width="345" alt="image" src="https://user-images.githubusercontent.com/56437682/92365825-43e12c80-f0ec-11ea-9014-7c637e985fa2.png">

#### Browsers affected
This issue was seen on Chrome (Version 85.0.4183.83 (Official Build) (64-bit)) and Edge (Version 85.0.564.44 (Official build) (64-bit)) 

Note: Also tested on Firefox (80.0.1 (64-bit)) and Safari (Version 13.1.2 (15609.3.5.1.3)), both were unaffected
 by this issue

**Comment by SimonFinney** [comment]
Resolved in #810
