### ISSUE TITLE
Checkbox component loading skeleton appears to be static

### ISSUE THREAD

**Issue by sharon-oboyle** [carbon-design-system/ibm-security#750]
## Bug - Checkbox component loading skeleton appears to be static

**Expected behavior -**

Clearly see it is loading when page is loaded

**Actual behavior -**
Contrast on the comoponent is not enough, so that you can only tell it is loading after zooming in multiple times

### Steps for reproducing

1.  View the component here: https://ibm-security.carbondesignsystem.com/?path=/story/components-checkbox–skeleton
2.  Check does it look like it's actually loading dynamically

### Screenshots

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56437682/92492936-dc120b00-f1eb-11ea-8950-75ec64dd2cc0.png">

**Comment by SharonOBoyle** [comment]
Hi @SimonFinney, is there any update for this issue?

**Comment by SimonFinney** [comment]
Hey @SharonOBoyle - Thanks for raising! I investigated this and we inherit the skeleton styling directly from Carbon. It appears to be the same color across all components for the Gray 100 theme.

It's worth creating an issue in their repo to further discuss with that team whether the color tokens should be adjusted - https://github.com/carbon-design-system/carbon/issues/new/choose

**Comment by SharonOBoyle** [comment]
Hey @SimonFinney I created an issue here - please feel free to add / modify as I wasns't quite sure how to word it https://github.com/carbon-design-system/carbon/issues/7348
