### ISSUE TITLE
Sortable DataTable header has thin padding on hover

### ISSUE THREAD

**Issue by lidiya101** [carbon-design-system/ibm-security#753]
## Bug - on update from 1.22 version to 1.29 , the DataTable header label  has thin padding on hover.

**Expected behavior -**

on hover, the table header label should be fully highlighted.
![image](https://user-images.githubusercontent.com/6652483/92584031-6feae200-f293-11ea-93a3-9345d3eb0004.png)

**Actual behavior -**

 only a thin line of highlight on the label is observed
![image](https://user-images.githubusercontent.com/6652483/92583732-12569580-f293-11ea-9cd2-55802e87b51d.png)

### Steps for reproducing

1. Use sortable data table
2. hover on the header label

**Comment by SimonFinney** [comment]
Hi @lidiya101 - thanks for raising. Could you create a reduced test case in CodeSandbox to help debug the issue? https://codesandbox.io/s/github/carbon-design-system/ibm-security/tree/dev/examples/codesandbox
