### ISSUE TITLE
Bug - OverflowMenu onClose() not fired when Overflow menu clicked when menu is open

### ISSUE THREAD

**Issue by alancoff** [carbon-design-system/ibm-security#754]
## Bug - 

**Expected behavior -**

Clicking the Overflow menu button when the menu is open/displayed, closes the menu and fires the onClose function 

**Actual behavior -**

Clicking the Overflow menu button when the menu is open, closes the menu but does not fire the onClose function.
Clicking any other area of the screen will fire the onClose function   

### Steps for reproducing

https://codesandbox.io/s/codesandbox-forked-5n1zk

1.  Open the Overflow menu by clicking the Overflow menu button 
2.  Close the Overflow menu by clicking the same Overflow menu button 
3.  Notice onClose not called 

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -** 1.29.0

**Comment by diego-codes** [comment]
This has been resolved in `carbon-components-react`: https://github.com/carbon-design-system/carbon/issues/6692. However, those changes have not made it to this package yet.
