### ISSUE TITLE
Facing issue with “@carbon/ibm-security”: “1.29.0” version on Firefox 68.12.0esr

### ISSUE THREAD

**Issue by palak1459** [carbon-design-system/ibm-security#759]
## Bug - Getting error as “ResizeObserver is not a constructor” when using `<DataTable/>` or `<ScrollGradient/>` on Firefox 68.12.0esr.
It says error occurred on `node_modules/@carbon/ibm-security/lib/components/ScrollGradient/ScrollGradient.js`
When I downgraded the version to “@carbon/ibm-security”: “1.22.1”, it worked fine. 

**Expected behavior -**

components of “@carbon/ibm-security”: “1.29.0” should work for Firefox esr versions.

**Actual behavior -**

<DataTable/> and <ScrollGradient/> should work on Firefox ESR version.

### Steps for reproducing

Use <DataTable/> and <ScrollGradient/> component on Firefox ESR version.

#### 
<img width="1141" alt="Screenshot 2020-09-08 at 8 20 42 PM" src="https://user-images.githubusercontent.com/71092117/92770110-3ca17380-f3b7-11ea-8143-0a20a997be28.png">

### Affected browsers

**Firefox 68.12.0esr**

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
I believe this should be resolved in https://github.com/carbon-design-system/ibm-security/releases/tag/v1.31.0
