### ISSUE TITLE
Button - all props are not displayed in Storybook proptable

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#76]
## Bug - 

**Expected behavior -**

All `Button` props are shown in the storybook prop table.

**Actual behavior -**

Only two of the many `Button` props are shown in the storybook prop table: https://ibm-security.carbondesignsystem.com/?path=/story/components-button--default

### Optional information

**Version -** `1.1.0`

**Comment by b3nk3** [comment]
I'd like to pick this up.

**Comment by SimonFinney** [comment]
@b3nk3 - If this is still available by October 1, consider it yours

**Comment by SimonFinney** [comment]
Closing in favor of #134
