### ISSUE TITLE
Shell (Security) Component, react build > `href error`

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/ibm-security#767]
## Bug - When buying React build everything is fine. However, when I click the Shell Menu, I get an error.

**Expected behavior -**

not to take error

**Actual behavior -**
the screen turns white
and
console error mesage;
react-dom.production.min.js:5058 TypeError: Cannot read property 'href' of undefined
    at NavList.js:47
    at Array.filter (<anonymous>)

### Screenshots
![error](https://raw.githubusercontent.com/11315K/carbon-build-test-error/react-step-2/error-gif.gif)

https://github.com/11315K/carbon-build-test-error/

**Comment by faabiopontes** [comment]
May I?

**Comment by faabiopontes** [comment]
Omg this error is so crazy

**Comment by faabiopontes** [comment]
Could you please try to reproduce this error on an updated version of the packages? It seems to be something related to the `create-react-app` version of it, and when I remove the packages from `.yarn-offline-mirror` and try to install it all from the source it breaks even on development, something related to a missing `mainNavigation` inside the `labels` object

**Comment by SimonFinney** [comment]
Hi @faabiopontes ! It looks like the original author has been deleted by GitHub, so I'm going to remove the 'hacktoberfest' label for now until we receive further information on the issue

**Comment by faabiopontes** [comment]
Ok @SimonFinney.

I think the issue can be closed, the repository where the problems happened was very outdated and doesn't exist anymore too (since the user is a ghost now)
