### ISSUE TITLE
Bug [ComboButton] : combo button is broken when used inside the DataTable 

### ISSUE THREAD

**Issue by Deriohig** [carbon-design-system/ibm-security#770]
## Bug - 
When using the ComboButton inside the DataTable's TableToolbarContent and opening the dropdown menu it seems to break the TableToolbar component... the menu doesn't show up and the whole toolbar gets hidden by what looks like an empty BatchActions bar

**Expected behavior -**

Combo button works as normal with the Datatable toolbar

**Actual behavior -**

 the dropdown menu it seems to break the TableToolbar component.

### Steps for reproducing

https://codesandbox.io/s/wandering-worker-qedqq?file=/src/index.js

step1 : use the combobutton in the sandbox 

### Affected browsers

all
### Optional information

**Version -**  v1.32.0

**Comment by avainch** [comment]
Is there an ETA on this issue?  This bug is still very relevant for Guardium Insights.

**Comment by SimonFinney** [comment]
@avainch For this I'll need to investigate some changes to the `ComboButton`, but I believe @Deriohig has a workaround that can be leveraged for the time being

**Comment by SimonFinney** [comment]
Resolved in latest as per https://codesandbox.io/s/blissful-shamir-3740g
