### ISSUE TITLE
Notification banner and Protal can't be closed when Panel2 is opened. And multiple event listeners cause OverflowMenu acting incorrectly.

### ISSUE THREAD

**Issue by JennChao** [carbon-design-system/ibm-security#800]
## Bug - Click event doesn't work properly
Notification banner and Protal can't be closed when Panel2 is opened. 
And multiple event listeners cause OverflowMenu acting incorrectly.

https://ibm-security.slack.com/archives/CRV39QKP0/p1603179373069100?thread_ts=1603101457.058200&cid=CRV39QKP0
https://ibm-security.slack.com/archives/CRV39QKP0/p1603180195069600?thread_ts=1603101457.058200&cid=CRV39QKP0

**Expected behavior -**
Notification banner and Protal should be able to be closed when Panel2 is opened. 
OverflowMenu should detect user click event correctly. 

**Actual behavior -**
With Panel2 opened, any click action towards Notification banner and Protal doesn't seem to be detected.
With Panel2 opened, when `onClose` event sometimes seems to be detected two times which cause OverflowMenu's option items can't be hidden as user wants it to.

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  
2.  
3.  

#### 

![]()

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
The solution for this is will be to expose `focusTrapOptions` as a prop on `DataDecorator` so it can be consumed by `PanelV2` and `Portal` respectively - PR to come this week
