### ISSUE TITLE
Calulation of height for ScrollGradient

### ISSUE THREAD

**Issue by JennChao** [carbon-design-system/ibm-security#826]
## Bug - 
Unexpected scroll gradient appears when resizing browser.
![scroll_gradient_bug](https://user-images.githubusercontent.com/23396970/98218661-fd426e00-1f86-11eb-8591-31feed0397a2.gif)

**Expected behavior -**

No scroll gradient should appear when resizing browser.

**Actual behavior -**

Please see the demo video above.

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  Storybook for reproducing issue. https://pages.github.ibm.com/investigate/investigate/?path=/story/querycard--running.
2.  Please follow steps in the video to reproduce the issue.
3.  

#### 

![]()

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by JennChao** [comment]
@SimonFinney 
Possible solution in DE's PR.
https://github.ibm.com/investigate/investigate/pull/3721

**Comment by hlyang397** [comment]
Not 100% sure, but It looks like a bug from carbon/ibm-security ScrollGradient component which determines if the scroll gradient needs to display or not. (edge value computation).
