### ISSUE TITLE
Combo Button Behavior 

### ISSUE THREAD

**Issue by areddon** [carbon-design-system/ibm-security#84]
### Details

I would like to start a discussion on the behavior of the new [Combo Button](https://ibm-security.carbondesignsystem.com/?path=/story/patterns-combobutton--default) component.

### Current Behavior

When selecting an alternative action from the dropdown, the alternative action is fired and the default button action remains unchanged.

### Proposed Behavior

When selecting an alternative action from the dropdown, the action is not fired and the default button action is replaced alternative.

Then the user can click the button to fire the alternative action.

Allow the consumer to specify the default action, such that when the user changes it, the interface can remember it for next time.

The proposed behavior matches that of the GitHub merge/squash/rebase button on pull requests.

**Comment by SimonFinney** [comment]
@jimmydyer how do you feel about this proposed change?

**Comment by jimmydyer** [comment]
@SimonFinney I disagree with this proposal. The primary action shouldn't be replaced, that's why it's the primary action. The combo button isn't a select component. It's a way to take primary and secondary actions on an object in a concise way. If a user selects from the dropdown within the combo button, then the action is fired on that selected option.

**Comment by SimonFinney** [comment]
That's valid - From my understanding, the key differentiator of this is its 'memory'...

If someone continuously typically selects the secondary action, doesn't that make it that user's primary action? I'm missing the in-product context here

**Comment by jimmydyer** [comment]
Potentially, but I don't want to change the intent of the component until we do more user testing here. I also don't want to be the one person to decide this :). Let get Josh Kimmel and Cameron Calder on this discussion as well.

**Comment by cameroncalder** [comment]
Here's my take. There are valid points being brought up on both sides in this thread. I can see how switching the primary to another action based on user behavior would be advantageous. But I also wonder if it may be jarring/unexpected if this happens automatically or if this happens after a single time. Perhaps another way to think about it is to surface the decision to the user and allow them to make the change. _Example: Third time a user engages the same option in the combo button a prompt displays asking them if they'd like to switch the primary to that option._ Now I can't speak to the technical implications for this level of behavior tracking, but empowering the user to make the decision may be a direction worth exploring

**Comment by jendowns** [comment]
Hey everyone, I just wanted to point out that when we talk about "memory" and the `ComboButton` being adjusted depending on past user behavior / preferences, that would be more appropriate to handle on the application's side of things -- in other words, when an application uses this component, they would need to make a decision about how they want to "remember" past user preferences & re-render the `ComboButton` to accommodate those preferences. The `ComboButton` would not maintain this information on its own & only just renders the options it's told to render.

**Comment by areddon** [comment]
@jendowns is correct, the memory is really on the application. The proposed change comes down to selecting a different action and having it replace the contents of the button without firing.
