### ISSUE TITLE
Wrong position of OverflowMenu options and scrolling up the whole page while clicking on OverflowMenu

### ISSUE THREAD

**Issue by JennChao** [carbon-design-system/ibm-security#841]
## Bug - Wrong position of OverflowMenu options and scrolling up the whole page while clicking on OverflowMenu

**Expected behavior -**

1. Position of OverflowMenu options should be next to OverflowMenu.
2. Opens up OverflowMenu options shouldn't cause the scrolling of the whole page.

**Actual behavior -**
Please see the attached video.
[overflow-menu-click-and-scroll.gif.zip](https://github.com/carbon-design-system/ibm-security/files/5551580/overflow-menu-click-and-scroll.gif.zip)

When clicking on the first oeverflow menu button, the "Add to case" overflow menu option shows up at the bottom of the page.
<img width="1213" alt="圖片" src="https://user-images.githubusercontent.com/23396970/99353287-2516c780-28df-11eb-93a1-7817764fc28e.png">

### Steps for reproducing

[CodeSandbox](https://codesandbox.io/s/)

1.  
2.  
3.  

#### 

![]()

#### 

![]()

#### 

![]()

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](http://browserl.ist/?q=%3E+1%25%2C+not+IE+11)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by JennChao** [comment]
@SimonFinney 
This issue is highly related to the following issue in Carbon.
Please help to track it. Thanks!
https://github.com/carbon-design-system/carbon/issues/7308

**Comment by codewood** [comment]
@SimonFinney Looks like Carbon merged a fix. Has ibm-security pulled it in yet? Also happy new year!! :)
