### ISSUE TITLE
Proposal: ComboButton —— Allow primary action link to open in a new tab

### ISSUE THREAD

**Issue by ShayMurnin** [carbon-design-system/ibm-security#845]
### Description
Currently we can open `ComboButton` menu items links in a new tab as it allows for spreading props on each item. However this is currently not possible for the primary action itself (when it is a link).

See screenshots below. I think I'll put a PR for this today.

#### As-is
![combo-button__as-is](https://user-images.githubusercontent.com/15728451/100223149-033ac780-2f13-11eb-8d05-18ba52db2fdf.gif)

#### Proposed to-be
![combo-button__to-be](https://user-images.githubusercontent.com/15728451/100223362-514fcb00-2f13-11eb-95d2-0d3d57ec356d.gif)

### Acceptance criteria

- [ ] `target="_blank"` can be added as a prop to the primary action

#### Accessibility

- [ ] Semantic HTML is used by default where relevant, with ARIA attributes used as required
- [ ] No violations produced as a result of automated accessibility tests

#### Breakpoints

- [ ] Mobile, tablet, and desktop, if applicable

#### Browser support

- [ ] [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

#### Documentation

- [ ] `defaultProps` and `propTypes` are included as part of component definitions, and documented in a human-readable format

#### Internationalization

- [ ] No hardcoded text exposed to the user, even with screen readers

#### Sass

- [ ] Follows the directory structure and naming convention, or provides a good justification for changing it

#### Storybook

- [ ] Stories that capture features of the component
- [ ] Provide controls for customising features of the component

#### Tests

- [ ] Tests are behaviour-driven and written similarly to how a user would interact with the component
- [ ] Automated accessibility tests

**Comment by SimonFinney** [comment]
@ShayMurnin Thanks for raising! This makes sense to me
