### ISSUE TITLE
Bug: Some components' width are shortened and truncated after upgrade to latest Carbon. 

### ISSUE THREAD

**Issue by JennChao** [carbon-design-system/ibm-security#846]
### Description

After upgrading Carbon Security to `1.35.1-prerelease.1`, width of `OverflowMenu` component no longer got calculated correctly.

`OverflowMenu` component:
<img width="656" alt="圖片" src="https://user-images.githubusercontent.com/23396970/100306311-15ce0300-2fde-11eb-8d03-34330c204902.png">

`OverflowMenu` component:
<img width="318" alt="圖片" src="https://user-images.githubusercontent.com/23396970/100306334-22eaf200-2fde-11eb-89ae-7d4ae349ed65.png">

**Comment by SimonFinney** [comment]
It looks like the recommendation is to now use `width: auto` for `OverflowMenu` custom triggers - https://react.carbondesignsystem.com/?path=/story/overflowmenu--custom-trigger
