### ISSUE TITLE
Add React 'List' component for 'Carbon for Security'

### ISSUE THREAD

**Issue by jimmydyer** [carbon-design-system/ibm-security#85]
### Details

- **Application / team -** Threat Ops team
- **Work item -** []()
- **Needed by -** October 1, 2019?

### Proposal

Currently, the IBM Design Language has a point-of-view on how list items (bullets, dashes, etc.) should be created/visualized in a UI, but the Carbon doesn't have a REACT version of this. The proposal is to create a React version and make it available in Carbon for Security's repo so that we can utilize this design direction in our UI.

https://www.carbondesignsystem.com/components/list/code

>
![Carbon_Design_System_–_List](https://user-images.githubusercontent.com/54411478/65159685-18a48f80-d9fa-11e9-8b05-ff169765e2e5.png)

**Comment by b3nk3** [comment]
I'd like to pick this up

**Comment by SimonFinney** [comment]
@b3nk3 - If this is still available by October 1, consider it yours
