### ISSUE TITLE
Quick search action within data table component is confusing to users

### ISSUE THREAD

**Issue by jimmydyer** [carbon-design-system/ibm-security#864]
### In multiple usability tests, users are clicking the empty bar above the data table to try and initiate a search and are getting confused because they expect the full bar to be clickable.

![Playbooks_and_Cisco_Webex_Meetings](https://user-images.githubusercontent.com/54411478/101805189-15eafa00-3ad8-11eb-973b-46d9b7f4a6a4.png)

**Comment by cameroncalder** [comment]
To align with Carbon, the bar should not be visible
https://www.carbondesignsystem.com/components/data-table/usage#formatting
https://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar

**Comment by SimonFinney** [comment]
This is a given when using a toolbar with the `DataTable` - the only difference in our example is that we're not providing supplementary text. See our example in the cool gray 10 theme:

![Toolbar](https://user-images.githubusercontent.com/3846874/101808522-582f2e00-3b0e-11eb-97bd-4eabd4b9d50d.png)

And Carbon's if I remove the supplementary text:

![Carbon](https://user-images.githubusercontent.com/3846874/101808680-89a7f980-3b0e-11eb-8266-2206d964e678.png)

We can of course override the background color ourselves, but to prevent deviation my recommendation here is to start a discussion with the Carbon team and share the usability findings with them.
