### ISSUE TITLE
Use `@storybook/addons-docs`

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#87]
Replace the info plugin with `@storybook/addon-docs`: https://www.npmjs.com/package/@storybook/addon-docs

May involve removing some story-specific `docgen` customization.

**Comment by jendowns** [comment]
SCOPE: Note that this change will only be able to happen for non-proxied components 

The proxied components will need to be converted by Carbon and then hopefully, soon-ish, we can start importing them directly 🤔

**Comment by SimonFinney** [comment]
@jendowns Nice idea! Could you explore implementing this plugin with one of our more elaborate components first, for example, the `Wizard`? This way we can evaluate it before making changes across the board.

**Comment by jendowns** [comment]
@SimonFinney I was actually thinking of going the opposite direction 😆 Implementing MDX with a simple component, like the `Pill`. Ideally (and theoretically), `jsx` and `mdx` stories could live side by side. So I was thinking, to get this effort off the ground, I could set up `mdx` story processing & show an example with something like the `Pill`, then we could split the work of converting the rest of the non-proxied components. The `Wizard` is the most complex story we have, I believe, so I didn't want to experiment with that one first. 😅

**Comment by SimonFinney** [comment]
That's a fair point, and I understand. I think in a situation like this where we're proposing a change in how we do documentation, we'll, of course, need an example of something simple, but we also need to investigate something complex, so we have a better understanding of how something like this scales before committing to the technology.

I don't feel comfortable making commitments to convert all components before evaluating whether it works for more complex patterns, especially as we move towards building more of those out! 😅

**Comment by jendowns** [comment]
On this topic: previously this effort, in general, has been identified by both us and the Carbon team as a pre-requisite for importing proxied-component stories from Carbon.
