### ISSUE TITLE
Tags inside input fields

### ISSUE THREAD

**Issue by lordsfantasy** [carbon-design-system/ibm-security#884]
The user input should get converted into tags within input field itself. Please refer below example.
![image](https://user-images.githubusercontent.com/60696896/104177465-ced18b00-542e-11eb-9557-2d17cd3c70ff.png)

**Comment by SimonFinney** [comment]
Hello @lordsfantasy ! Thanks for raising - is this a proposal for an enhancement that you wish to submit a PR for?

As the Carbon core team own both the `Tag` and `TextInput` component, I recommend you open that request there - https://github.com/carbon-design-system/carbon/issues/new?assignees=&labels=type%3A+enhancement+%F0%9F%92%A1&template=feature-request-or-enhancement.md&title=
