### ISSUE TITLE
Carbon Line Graph Legend Placements Sticky Hover Help and ordering of Legends

### ISSUE THREAD

**Issue by sunilmge** [carbon-design-system/ibm-security#889]
### Description 
There are bugs related to sticky tooltip/hover help and appearance of hover help. The legends need to be positioned on the bottom left and the hover help back ground and text do not follow UI coding standards.

We use the following in IBM Security Vefify
carbon-addons-data-viz-react/cjs/components/LineGraph/LineGraph'

1) The hover hep sometimes becomes sticky when moving the mouse over the graph points
2) The position of the legends should be moved to bottom left to avoid loosing context
3) When we re-order the legend labels, the data gets mixed up. We need a way for the data to be bound to the legend label so that we can re-order the legend labels and the data gets mapped accordingly.

![image](https://user-images.githubusercontent.com/75816575/105452800-aa956a00-5cca-11eb-9827-78425be98a10.png)

- Notice how the Hover help on the graph remains sticky even after moving away from the graph
- The Legends Low, High Medium and Very High should be moved to the bottom left as user will loose context especially in wide screens
- The hover help appears in a black background, they must be light and the text should appear legible against the light background
- The legends can appear dynamically based on the data set. In this case the legends are Low, High, Medium and Very High. If we reorder the legends the data gets mixed up. We need a way to bind data to the legend names so that when we re-order legends, the data should gets bound to the new position of the legend. Else we get a case wherein High data gets mapped to Low etc when re-ordering legends

#### Expected behavior

Tooltips should only appear when the user is hovering over that specific data point, and they should not be sticky at any point.

Follow the styling that's in Carbon for our tooltips. Currently, they're on a dark background and the spacing is off. They should be on a light background–this is because the colors that we use in those charts are different on a cool gray 10 background than they are on a cool gray 100.

Let's also move the legend (the squares w/ colors and labels) to the bottom left of the chart. This is because when we were reviewing the chart on Sunil's monitor yesterday, he had a wide screen (as I'm sure a lot of users do) and the legend was so far to the right that it loses context into what the user is viewing. Positioning it on the bottom left will help the user understand the content of the chart at a glance. 

The legend is out of order (I think High should sit next to Very High). There is no way to re-order the legends as the data is not bond to the legend labels

#### Actual behavior

- Tool tip is sticky when moving the mouse over the graph
- The tooltip background in black and does not follow UI guidelines in terms of light back ground and spacing of text
- The Legends do not appear bottom left and hence loose context easily
- When we reorder legend labels, the data does not get swapped accordingly, we must be able to re-order legend labels and not result in data mix up.

### Steps for reproducing

1) Login to IBM Security Verify with Adaptive Access with CIAA subscription. Browse to /ui/admin and choose Reports -> Adaptive Access to recreate.

### Affected browsers

All browsers

### Optional information

NA

**Comment by SimonFinney** [comment]
Hi @sunilmge ! This is an unusual request for this repo - please reach out to me on Slack (`@simon`) and I'll try point you in the right direction
