### ISSUE TITLE
ICA Size Large

### ISSUE THREAD

**Issue by CassidyJensen** [carbon-design-system/ibm-security#907]
### Description

The ICA / ICAModule needs a large size variation. An additional variable can be supplied to ICA in order to change the size from the default settings. The large version of the ICA uses $heading-06 for the value and $heading-03 for the total. Are there any other requirements / changes for the large version?

![image](https://user-images.githubusercontent.com/45407808/109023877-66570a00-767a-11eb-91b3-5cd61cdc3412.png)

### Goals / Use cases

- [ ] Provide alternative way to display ICA

**Comment by SimonFinney** [comment]
@cameroncalder - @CassidyJensen has kindly stepped up to contribute this piece! 🎉

My only thought here is - are there other size variations beyond a large ICA? If so, it might make sense to expose `size` prop similar to [Carbon's `Button`](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L178).

**Comment by cameroncalder** [comment]
@CassidyJensen @SimonFinney Hey, this is great to hear! These are the sizes we'd need plus the specs (Default, Large, Xlarge)

![Artboard](https://user-images.githubusercontent.com/50155706/109040548-a37bc600-7693-11eb-945f-23a856de6533.png)

**Comment by SimonFinney** [comment]
> @CassidyJensen @SimonFinney Hey, this is great to hear! These are the sizes we'd need plus the specs (Default, Large, Xlarge)
> 
> ![Artboard](https://user-images.githubusercontent.com/50155706/109040548-a37bc600-7693-11eb-945f-23a856de6533.png)

Awesome - thanks! We'll need to create a separate issue for the 'trending' arrow, but I believe this will cover it for sizes.

**Comment by CassidyJensen** [comment]
@SimonFinney 
Since this is my first time contributing I want to check a couple things. First, should I create a story case for the sizes? I created one for testing, but I wasn't sure if it needed to stay permanently. 

Secondly, I ran` yarn test` and I am getting 2 snapshot errors. What can I do to fix it? Should I run `yarn run jest -u` or does it indicate a problem with my code?

![image](https://user-images.githubusercontent.com/45407808/109233156-9e4b7380-7786-11eb-8e43-3f6ca6c95077.png)
![image](https://user-images.githubusercontent.com/45407808/109233182-ac00f900-7786-11eb-887d-c9e4ae601025.png)

**Comment by SimonFinney** [comment]
> @SimonFinney
> Since this is my first time contributing I want to check a couple things. First, should I create a story case for the sizes? I created one for testing, but I wasn't sure if it needed to stay permanently.
> 
> Secondly, I ran` yarn test` and I am getting 2 snapshot errors. What can I do to fix it? Should I run `yarn run jest -u` or does it indicate a problem with my code?
> 
> ![image](https://user-images.githubusercontent.com/45407808/109233156-9e4b7380-7786-11eb-8e43-3f6ca6c95077.png)
> ![image](https://user-images.githubusercontent.com/45407808/109233182-ac00f900-7786-11eb-887d-c9e4ae601025.png)

Thank you!

1. As this is a modifier, adding a [knob](https://www.npmjs.com/package/@storybook/addon-knobs) should be sufficient here
2. That's exactly right! `yarn test -u` should update these snapshots - they're in place to verify changes to the public CSS and JavaScript output

**Comment by CassidyJensen** [comment]
> 1. As this is a modifier, adding a [knob](https://www.npmjs.com/package/@storybook/addon-knobs) should be sufficient here
> 2. That's exactly right! `yarn test -u` should update these snapshots - they're in place to verify changes to the public CSS and JavaScript output

Thank you!

**Comment by SimonFinney** [comment]
Reopening to track unit tests
