### ISSUE TITLE
`ICA` trending variant

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-security#908]
> @CassidyJensen @SimonFinney Hey, this is great to hear! These are the sizes we'd need plus the specs (Default, Large, Xlarge)
> 
> ![Artboard](https://user-images.githubusercontent.com/50155706/109040548-a37bc600-7693-11eb-945f-23a856de6533.png)

Awesome - thanks! We'll need to create a separate issue for the 'trending' arrow, but I believe this will cover it for sizes.

_Originally posted by @SimonFinney in https://github.com/carbon-design-system/ibm-security/issues/907#issuecomment-785765365_

**Comment by CassidyJensen** [comment]
@cameroncalder In the case of being used on the ICAModule - how should the trending arrow appear? 

The default appearance is in a column, but it seems like it should be in a row with the value. I've added screenshots of the current and potential layouts below. 

![image](https://user-images.githubusercontent.com/45407808/109330175-9fc57c00-7818-11eb-9e68-b56d985590fd.png)
![image](https://user-images.githubusercontent.com/45407808/109331062-9dafed00-7819-11eb-8b4e-ff873a82b161.png)
![image](https://user-images.githubusercontent.com/45407808/109331221-d354d600-7819-11eb-986c-0a07589a74ac.png)

**Comment by cameroncalder** [comment]
@CassidyJensen The bottom version would be preferred
