### ISSUE TITLE
Return to in Shell component is hardcoded

### ISSUE THREAD

**Issue by joemc11** [carbon-design-system/ibm-security#909]
### Description
Return to is hardcoded in https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/Shell/Shell.js

![]()
<img width="1194" alt="Screenshot 2021-02-26 at 11 02 14" src="https://user-images.githubusercontent.com/14826627/109292355-2599f500-7822-11eb-8e25-03e3c3cae22e.png">

### Acceptance criteria

- [ ] 

#### Accessibility

- [ ] Semantic HTML is used by default where relevant, with ARIA attributes used as required
- [ ] No violations produced as a result of automated accessibility tests

#### Breakpoints

- [ ] Mobile, tablet, and desktop, if applicable

#### Browser support

- [ ] [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

#### Documentation

- [ ] `defaultProps` and `propTypes` are included as part of component definitions, and documented in a human-readable format

#### Internationalization

- [ ] No hardcoded text exposed to the user, even with screen readers

#### Sass

- [ ] Follows the directory structure and naming convention, or provides a good justification for changing it

#### Storybook

- [ ] Stories that capture features of the component
- [ ] Provide controls for customising features of the component

#### Tests

- [ ] Tests are behaviour-driven and written similarly to how a user would interact with the component
- [ ] Automated accessibility tests

**Comment by SimonFinney** [comment]
@joemc11 Thanks for raising! Per [this thread](https://ibm-security.slack.com/archives/CRV39QKP0/p1614173212008200), let me know how I can enable a small contribution.

**Comment by sstewart199** [comment]
@joemc11 @SimonFinney how far did we get with this piece? @SimonFinney is there something you need from our end?

**Comment by joemc11** [comment]
Can this be repoened, still an issue
