### ISSUE TITLE
Pagination component, items per page list goes white when changing Value (Windows only)

### ISSUE THREAD

**Issue by Pasoon** [carbon-design-system/ibm-security#927]
### Description

Pagination component, when using the items per page list, the background goes white making it impossible to see the options. This is only happening on Windows, it works fine on Mac. This issue can also be recreated in the storybook by scrolling several times. On UCM it happens right away. 

![image](https://user-images.githubusercontent.com/17908476/113895843-59f4bf80-9797-11eb-817b-a0461ad06f0a.png)

#### Expected behavior

Item per page background should not go white. 

#### Actual behavior

Item per page background is going white. 

### Steps for reproducing

1. Login to QRadar
2. Click Use Case Manager tab
3. Go to the bottom of the Use Case Explorer Table
4. Click items per page and hover over the options going up and down the list.
5. Items should go white. 

Can also be done on pagination component in storybook, just need to hover and scroll several times. 

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

Chrome on Windows 10

**Comment by SimonFinney** [comment]
Hi @Pasoon - does this also exist in https://react.carbondesignsystem.com ?

**Comment by SimonFinney** [comment]
Blocked pending thread in https://ibm-security.slack.com/archives/C0M053VPT/p1620809570250200
