### ISSUE TITLE
TruncatedList with TypeLayout causing aria issues

### ISSUE THREAD

**Issue by joemc11** [carbon-design-system/ibm-security#954]
## Bug - 
Run the attached unit test and see the following aria issues
This work's in version 1.39.0, broke in versions 1.40.0 and above  This is blocking us from upgrading.

<img width="861" alt="Screenshot 2021-04-29 at 12 03 44" src="https://user-images.githubusercontent.com/14826627/116541140-016e9900-a8e3-11eb-85a0-c0c29bf54469.png">

### Description

[TypeLayout.txt](https://github.com/carbon-design-system/ibm-security/files/6398069/TypeLayout.txt)

![]()

### Steps for reproducing

1. 

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
@joemc11 Was this not resolved with https://github.com/carbon-design-system/ibm-security/pull/950 ? Would you mind providing an implementation example?

**Comment by joemc11** [comment]
@SimonFinney Rename attached TypeLayout.txt to TypeLayout.js, would not let be upload a .js file. We are using axe-core version 4.2.0

**Comment by joemc11** [comment]
Can this ticket be prioritised please, we are stuck on version 1.39.0 and version 1.42.0 is now out.

**Comment by SimonFinney** [comment]
Hi @joemc11 ! As I understand, for these components to be accessible, the `TypeLayoutBody` expects a `TypeLayoutRow` as a child - using a `TruncatedList` appears to have worked previously but given the accessibility improvements introduced upstream from Carbon, this looks like it's no longer supported.

Feel free to reach out on Slack to discuss this further, and I can work with you to accommodate a contribution to better support this edge case.

**Comment by joemc11** [comment]
Hardcoding roles row, cell and Table within TruncatedList.js resolves the avt issues, though this is not a valid solution.
![Screenshot 2021-09-21 at 09 41 53](https://user-images.githubusercontent.com/14826627/134143581-2b941ea4-d7ae-4918-9ba3-6cb9995af710.png)
n.
