### ISSUE TITLE
AVT issue in RadioButtonGroup

### ISSUE THREAD

**Issue by joemc11** [carbon-design-system/ibm-security#955]
## Bug - 
RadioButtonGroup works in version 1.39.0, broke in version 1.40.0 and above.  This is blocking us from upgrading.
<img width="690" alt="Screenshot 2021-04-29 at 13 15 56" src="https://user-images.githubusercontent.com/14826627/116549199-1b14de00-a8ed-11eb-80d6-5fac140c627c.png">

[RadioButtonGroup.txt](https://github.com/carbon-design-system/ibm-security/files/6398431/RadioButtonGroup.txt)

### Description
Rename RadioButtonGroup.txt to RadioButtonGroup.js
Run unit test using  accessibility-checker version 3.1.6 and axe-core version 4.2.0

![]()

#### Expected behavior
Unit test to pass

#### Actual behavior
Unit test fails in version 1.40.0 or above

### Steps for reproducing

1. 

### Affected browsers

[What's my browser?](http://www.whatsmyua.com) and [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

- [ ]  / 
- [ ]  / 
- [ ]  / 

### Optional information

**Version -**

**Comment by SimonFinney** [comment]
@joemc11 Is https://github.com/carbon-design-system/carbon/pull/7846 related? Does leveraging `legendText` resolve your issue?

**Comment by joemc11** [comment]
@SimonFinney I updated prop legend to legendText and it works.  Thanks Simon.
