### ISSUE TITLE
Request - Button that accepts loading icon

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/ibm-security#96]
### Proposal

We have designs to implement that require essentially a `Button` with an icon component where the icon is a spinning loader.

I think the most ideal API for this would be to make use of the existing `renderIcon` prop of the `Button` component. Like so:

```jsx
import SpinLoading16 from '...';
import { Button } from '@carbon/ibm-security';

<Button renderIcon={SpinLoading16}>Waiting for data</Button>
```
### Goals / use cases

- [ ] Buttons that would display data that is still loading. We want to be able to display the button, but also indicate that the data is not ready yet.

**Comment by areddon** [comment]
I would suggest that a `spinner` or `loading` prop is placed on the button instead, that way we can ensure that the spinner matches the correct theme (gray10, gray90, etc) and `kind` (ghost, danger, etc) with relation to the `Button`'s style.

**Comment by jendowns** [comment]
@diego-codes @areddon Two quick questions --

* Would this spinning/loading icon be on the right or left side?
* With the designs you have, is it possible to ever have a spinning/loading icon on one side of the `Button`, and then maybe a different icon (an arrow, for example) on the other side?

**Comment by diego-codes** [comment]
The regular icons are also styled based on the `kind` so whatever mechanism is used to add the color styles could be used for the spinner icons as well. I don't think there would be a need to have a `loading` prop.

![image](https://user-images.githubusercontent.com/5973294/65542395-b99cba00-ded4-11e9-8eaf-5fa9eb4e8bee.png)
![image](https://user-images.githubusercontent.com/5973294/65542435-cae5c680-ded4-11e9-91dd-415d3cba1a0b.png)

**Comment by diego-codes** [comment]
I don't have a specific design to display, but it's basically setting the spinning icon as the icon of the button (on the right).

**Comment by areddon** [comment]
As long as the only style change required is the svg color, than spinner could be passed in.

The `summary-card` component places the spinner on the left side of the button.

**Comment by diego-codes** [comment]
That's a good point @areddon on the placement for the spinner, though the summary card is bit strange because the primary button's icon is always on the left which is not the norm.

**Comment by jendowns** [comment]
@diego-codes When a button is in a loading state, it is always a "ghost" button? Thinking of a situation where someone has a primary/secondary button and set `loading={true}` -- would be look like a ghost button in that? The primary buttons in particular would be strange with a loading spinner 🤔
