### ISSUE TITLE
Need Light Variant for Toggle Component

### ISSUE THREAD

**Issue by jimmydyer** [carbon-design-system/ibm-security#993]
### Description

The current Carbon toggle component doesn't have an option in the Knobs section of the Storybook to use a light variant. Below is a screenshot that shows this option for the text input component:

![image](https://user-images.githubusercontent.com/54411478/121244337-5bf50080-c864-11eb-9490-3db2ee020f85.png)

The current implementation of a disabled toggle on a gray-90 background is almost impossible for users to see. This is an issue because the toggle is a primary action for the user's workflow. See the image below:

![Jimmy-Test (1)](https://user-images.githubusercontent.com/54411478/121244614-b0987b80-c864-11eb-8247-a34701c7648d.png)

### Acceptance criteria

- [ ] Provide a light variant option for the toggle component

#### Accessibility

- [ ] Semantic HTML is used by default where relevant, with ARIA attributes used as required
- [ ] No violations produced as a result of automated accessibility tests

#### Breakpoints

- [ ] Mobile, tablet, and desktop, if applicable

#### Browser support

- [ ] [browserl.ist supported browsers](https://github.com/carbon-design-system/ibm-security/blob/master/package.json#L174-L178)

#### Documentation

- [ ] `defaultProps` and `propTypes` are included as part of component definitions, and documented in a human-readable format

#### Internationalization

- [ ] No hardcoded text exposed to the user, even with screen readers

#### Sass

- [ ] Follows the directory structure and naming convention, or provides a good justification for changing it

#### Storybook

- [ ] Stories that capture features of the component
- [ ] Provide controls for customising features of the component

#### Tests

- [ ] Tests are behaviour-driven and written similarly to how a user would interact with the component
- [ ] Automated accessibility tests

**Comment by SimonFinney** [comment]
Per https://ibm-security.slack.com/archives/CG5SCD84F/p1623227658032000?thread_ts=1623179183.027400&cid=CG5SCD84F , adjustments to disabled tokens will be absorbed via #953

**Comment by SimonFinney** [comment]
Resolved by #953
